// GERADO A PARTIR DO @iconify-json/lucide INSTALADO. Não edite à mão.
//
// A biblioteca real do ENSPACE passa de 50 mil ícones. Aqui são os 2128 do
// Lucide que existem offline neste repositório: suficiente para provar o
// padrão de busca e a virtualização, que é o que muda com escala.
//
// Cada entrada é [nome, termos de busca]. Os termos trazem o nome em inglês
// mais sinônimos em português para os conceitos que as pessoas procuram de
// verdade — o produto hoje só acha por slug em inglês.

/** Pares [nome do ícone, termos de busca]. */
export const biblioteca: readonly (readonly [string, string])[] = [
  ['a-arrow-down', 'a arrow down'],
  ['a-arrow-up', 'a arrow up'],
  ['a-large-small', 'a large small'],
  ['accessibility', 'accessibility'],
  ['activity', 'activity indicador batimento monitoramento'],
  ['activity-square', 'activity square'],
  ['ad', 'ad'],
  ['air-vent', 'air vent'],
  ['airplay', 'airplay'],
  ['alarm-check', 'alarm check'],
  ['alarm-clock', 'alarm clock'],
  ['alarm-clock-check', 'alarm clock check'],
  ['alarm-clock-minus', 'alarm clock minus'],
  ['alarm-clock-off', 'alarm clock off'],
  ['alarm-clock-plus', 'alarm clock plus'],
  ['alarm-minus', 'alarm minus'],
  ['alarm-plus', 'alarm plus'],
  ['alarm-smoke', 'alarm smoke'],
  ['album', 'album'],
  ['alert-circle', 'alert circle'],
  ['alert-octagon', 'alert octagon'],
  ['alert-triangle', 'alert triangle'],
  ['align-center', 'align center'],
  ['align-center-horizontal', 'align center horizontal'],
  ['align-center-vertical', 'align center vertical'],
  ['align-end-horizontal', 'align end horizontal'],
  ['align-end-vertical', 'align end vertical'],
  ['align-horizonal-distribute-center', 'align horizonal distribute center'],
  ['align-horizonal-distribute-end', 'align horizonal distribute end'],
  ['align-horizonal-distribute-start', 'align horizonal distribute start'],
  ['align-horizontal-distribute-center', 'align horizontal distribute center'],
  ['align-horizontal-distribute-end', 'align horizontal distribute end'],
  ['align-horizontal-distribute-start', 'align horizontal distribute start'],
  ['align-horizontal-justify-center', 'align horizontal justify center'],
  ['align-horizontal-justify-end', 'align horizontal justify end'],
  ['align-horizontal-justify-start', 'align horizontal justify start'],
  ['align-horizontal-space-around', 'align horizontal space around'],
  ['align-horizontal-space-between', 'align horizontal space between'],
  ['align-justify', 'align justify'],
  ['align-left', 'align left'],
  ['align-right', 'align right'],
  ['align-start-horizontal', 'align start horizontal'],
  ['align-start-vertical', 'align start vertical'],
  ['align-vertical-distribute-center', 'align vertical distribute center'],
  ['align-vertical-distribute-end', 'align vertical distribute end'],
  ['align-vertical-distribute-start', 'align vertical distribute start'],
  ['align-vertical-justify-center', 'align vertical justify center'],
  ['align-vertical-justify-end', 'align vertical justify end'],
  ['align-vertical-justify-start', 'align vertical justify start'],
  ['align-vertical-space-around', 'align vertical space around'],
  ['align-vertical-space-between', 'align vertical space between'],
  ['ambulance', 'ambulance'],
  ['ampersand', 'ampersand'],
  ['ampersands', 'ampersands'],
  ['amphora', 'amphora'],
  ['anchor', 'anchor'],
  ['angle', 'angle'],
  ['angry', 'angry'],
  ['annoyed', 'annoyed'],
  ['antenna', 'antenna'],
  ['anvil', 'anvil'],
  ['aperture', 'aperture'],
  ['app-window', 'app window'],
  ['app-window-mac', 'app window mac'],
  ['apple', 'apple'],
  ['archive', 'archive arquivo morto arquivar caixa'],
  ['archive-restore', 'archive restore'],
  ['archive-x', 'archive x'],
  ['area-chart', 'area chart'],
  ['armchair', 'armchair'],
  ['arrow-big-down', 'arrow big down'],
  ['arrow-big-down-dash', 'arrow big down dash'],
  ['arrow-big-left', 'arrow big left'],
  ['arrow-big-left-dash', 'arrow big left dash'],
  ['arrow-big-right', 'arrow big right'],
  ['arrow-big-right-dash', 'arrow big right dash'],
  ['arrow-big-up', 'arrow big up'],
  ['arrow-big-up-dash', 'arrow big up dash'],
  ['arrow-down', 'arrow down'],
  ['arrow-down-0-1', 'arrow down 0 1'],
  ['arrow-down-01', 'arrow down 01'],
  ['arrow-down-1-0', 'arrow down 1 0'],
  ['arrow-down-10', 'arrow down 10'],
  ['arrow-down-a-z', 'arrow down a z'],
  ['arrow-down-az', 'arrow down az'],
  ['arrow-down-circle', 'arrow down circle'],
  ['arrow-down-from-line', 'arrow down from line'],
  ['arrow-down-left', 'arrow down left'],
  ['arrow-down-left-from-circle', 'arrow down left from circle'],
  ['arrow-down-left-from-square', 'arrow down left from square'],
  ['arrow-down-left-square', 'arrow down left square'],
  ['arrow-down-narrow-wide', 'arrow down narrow wide'],
  ['arrow-down-right', 'arrow down right'],
  ['arrow-down-right-from-circle', 'arrow down right from circle'],
  ['arrow-down-right-from-square', 'arrow down right from square'],
  ['arrow-down-right-square', 'arrow down right square'],
  ['arrow-down-square', 'arrow down square'],
  ['arrow-down-to-dot', 'arrow down to dot'],
  ['arrow-down-to-line', 'arrow down to line'],
  ['arrow-down-up', 'arrow down up'],
  ['arrow-down-wide-narrow', 'arrow down wide narrow'],
  ['arrow-down-z-a', 'arrow down z a'],
  ['arrow-down-za', 'arrow down za'],
  ['arrow-left', 'arrow left'],
  ['arrow-left-circle', 'arrow left circle'],
  ['arrow-left-from-line', 'arrow left from line'],
  ['arrow-left-right', 'arrow left right'],
  ['arrow-left-square', 'arrow left square'],
  ['arrow-left-to-line', 'arrow left to line'],
  ['arrow-right', 'arrow right'],
  ['arrow-right-circle', 'arrow right circle'],
  ['arrow-right-from-line', 'arrow right from line'],
  ['arrow-right-left', 'arrow right left'],
  ['arrow-right-square', 'arrow right square'],
  ['arrow-right-to-line', 'arrow right to line'],
  ['arrow-up', 'arrow up'],
  ['arrow-up-0-1', 'arrow up 0 1'],
  ['arrow-up-01', 'arrow up 01'],
  ['arrow-up-1-0', 'arrow up 1 0'],
  ['arrow-up-10', 'arrow up 10'],
  ['arrow-up-a-z', 'arrow up a z'],
  ['arrow-up-az', 'arrow up az'],
  ['arrow-up-circle', 'arrow up circle'],
  ['arrow-up-down', 'arrow up down'],
  ['arrow-up-from-dot', 'arrow up from dot'],
  ['arrow-up-from-line', 'arrow up from line'],
  ['arrow-up-left', 'arrow up left'],
  ['arrow-up-left-from-circle', 'arrow up left from circle'],
  ['arrow-up-left-from-square', 'arrow up left from square'],
  ['arrow-up-left-square', 'arrow up left square'],
  ['arrow-up-narrow-wide', 'arrow up narrow wide'],
  ['arrow-up-right', 'arrow up right'],
  ['arrow-up-right-from-circle', 'arrow up right from circle'],
  ['arrow-up-right-from-square', 'arrow up right from square'],
  ['arrow-up-right-square', 'arrow up right square'],
  ['arrow-up-square', 'arrow up square'],
  ['arrow-up-to-line', 'arrow up to line'],
  ['arrow-up-wide-narrow', 'arrow up wide narrow'],
  ['arrow-up-z-a', 'arrow up z a'],
  ['arrow-up-za', 'arrow up za'],
  ['arrows-up-from-line', 'arrows up from line'],
  ['asterisk', 'asterisk'],
  ['asterisk-square', 'asterisk square'],
  ['astroid', 'astroid'],
  ['at-sign', 'at sign'],
  ['atom', 'atom'],
  ['audio-lines', 'audio lines'],
  ['audio-lines-off', 'audio lines off'],
  ['audio-lines-x', 'audio lines x'],
  ['audio-waveform', 'audio waveform'],
  ['award', 'award'],
  ['axe', 'axe'],
  ['axis-3-d', 'axis 3 d'],
  ['axis-3d', 'axis 3d'],
  ['baby', 'baby'],
  ['backpack', 'backpack'],
  ['badge', 'badge'],
  ['badge-alert', 'badge alert'],
  ['badge-cent', 'badge cent'],
  ['badge-check', 'badge check'],
  ['badge-dollar-sign', 'badge dollar sign'],
  ['badge-euro', 'badge euro'],
  ['badge-help', 'badge help'],
  ['badge-indian-rupee', 'badge indian rupee'],
  ['badge-info', 'badge info'],
  ['badge-japanese-yen', 'badge japanese yen'],
  ['badge-minus', 'badge minus'],
  ['badge-percent', 'badge percent'],
  ['badge-plus', 'badge plus'],
  ['badge-pound-sterling', 'badge pound sterling'],
  ['badge-question-mark', 'badge question mark'],
  ['badge-russian-ruble', 'badge russian ruble'],
  ['badge-swiss-franc', 'badge swiss franc'],
  ['badge-turkish-lira', 'badge turkish lira'],
  ['badge-x', 'badge x'],
  ['baggage-claim', 'baggage claim'],
  ['balloon', 'balloon'],
  ['ban', 'ban'],
  ['banana', 'banana'],
  ['bandage', 'bandage'],
  ['banknote', 'banknote dinheiro pagamento nota grana'],
  ['banknote-arrow-down', 'banknote arrow down'],
  ['banknote-arrow-up', 'banknote arrow up'],
  ['banknote-check', 'banknote check'],
  ['banknote-x', 'banknote x'],
  ['bar-chart', 'bar chart'],
  ['bar-chart-2', 'bar chart 2'],
  ['bar-chart-3', 'bar chart 3'],
  ['bar-chart-4', 'bar chart 4'],
  ['bar-chart-big', 'bar chart big'],
  ['bar-chart-horizontal', 'bar chart horizontal'],
  ['bar-chart-horizontal-big', 'bar chart horizontal big'],
  ['barcode', 'barcode'],
  ['barrel', 'barrel'],
  ['baseline', 'baseline'],
  ['bath', 'bath'],
  ['battery', 'battery'],
  ['battery-charging', 'battery charging'],
  ['battery-full', 'battery full'],
  ['battery-low', 'battery low'],
  ['battery-medium', 'battery medium'],
  ['battery-plus', 'battery plus'],
  ['battery-warning', 'battery warning'],
  ['beaker', 'beaker'],
  ['bean', 'bean'],
  ['bean-off', 'bean off'],
  ['bed', 'bed'],
  ['bed-double', 'bed double'],
  ['bed-single', 'bed single'],
  ['beef', 'beef'],
  ['beef-off', 'beef off'],
  ['beer', 'beer'],
  ['beer-off', 'beer off'],
  ['bell', 'bell sino notificacao aviso alerta'],
  ['bell-check', 'bell check'],
  ['bell-dot', 'bell dot'],
  ['bell-electric', 'bell electric'],
  ['bell-minus', 'bell minus'],
  ['bell-off', 'bell off'],
  ['bell-plus', 'bell plus'],
  ['bell-ring', 'bell ring'],
  ['between-horizonal-end', 'between horizonal end'],
  ['between-horizonal-start', 'between horizonal start'],
  ['between-horizontal-end', 'between horizontal end'],
  ['between-horizontal-start', 'between horizontal start'],
  ['between-vertical-end', 'between vertical end'],
  ['between-vertical-start', 'between vertical start'],
  ['biceps-flexed', 'biceps flexed'],
  ['bike', 'bike'],
  ['binary', 'binary'],
  ['binoculars', 'binoculars'],
  ['biohazard', 'biohazard'],
  ['bird', 'bird'],
  ['birdhouse', 'birdhouse'],
  ['bitcoin', 'bitcoin'],
  ['blend', 'blend'],
  ['blender', 'blender'],
  ['blinds', 'blinds'],
  ['blocks', 'blocks'],
  ['bluetooth', 'bluetooth'],
  ['bluetooth-connected', 'bluetooth connected'],
  ['bluetooth-off', 'bluetooth off'],
  ['bluetooth-searching', 'bluetooth searching'],
  ['bold', 'bold'],
  ['bolt', 'bolt'],
  ['bomb', 'bomb'],
  ['bone', 'bone'],
  ['bone-fracture', 'bone fracture'],
  ['book', 'book'],
  ['book-a', 'book a'],
  ['book-alert', 'book alert'],
  ['book-audio', 'book audio'],
  ['book-bookmark', 'book bookmark'],
  ['book-check', 'book check'],
  ['book-copy', 'book copy'],
  ['book-dashed', 'book dashed'],
  ['book-down', 'book down'],
  ['book-headphones', 'book headphones'],
  ['book-heart', 'book heart'],
  ['book-image', 'book image'],
  ['book-key', 'book key'],
  ['book-lock', 'book lock'],
  ['book-marked', 'book marked'],
  ['book-minus', 'book minus'],
  ['book-open', 'book open documentacao manual conhecimento livro'],
  ['book-open-check', 'book open check'],
  ['book-open-text', 'book open text'],
  ['book-plus', 'book plus'],
  ['book-search', 'book search'],
  ['book-template', 'book template'],
  ['book-text', 'book text'],
  ['book-type', 'book type'],
  ['book-up', 'book up'],
  ['book-up-2', 'book up 2'],
  ['book-user', 'book user'],
  ['book-x', 'book x'],
  ['bookmark', 'bookmark'],
  ['bookmark-check', 'bookmark check'],
  ['bookmark-minus', 'bookmark minus'],
  ['bookmark-off', 'bookmark off'],
  ['bookmark-plus', 'bookmark plus'],
  ['bookmark-x', 'bookmark x'],
  ['boom-box', 'boom box'],
  ['bot', 'bot robo automacao ia agente'],
  ['bot-message-square', 'bot message square'],
  ['bot-off', 'bot off'],
  ['bottle-wine', 'bottle wine'],
  ['bow-arrow', 'bow arrow'],
  ['box', 'box'],
  ['box-select', 'box select'],
  ['boxes', 'boxes'],
  ['braces', 'braces'],
  ['brackets', 'brackets'],
  ['brain', 'brain'],
  ['brain-circuit', 'brain circuit'],
  ['brain-cog', 'brain cog'],
  ['brick-wall', 'brick wall'],
  ['brick-wall-fire', 'brick wall fire'],
  ['brick-wall-shield', 'brick wall shield'],
  ['bridge', 'bridge'],
  ['briefcase', 'briefcase trabalho maleta negocio'],
  ['briefcase-business', 'briefcase business'],
  ['briefcase-conveyor-belt', 'briefcase conveyor belt'],
  ['briefcase-medical', 'briefcase medical'],
  ['bring-to-front', 'bring to front'],
  ['broccoli', 'broccoli'],
  ['broom', 'broom'],
  ['broom-sparkles', 'broom sparkles'],
  ['brush', 'brush'],
  ['brush-cleaning', 'brush cleaning'],
  ['bubbles', 'bubbles'],
  ['bug', 'bug'],
  ['bug-off', 'bug off'],
  ['bug-play', 'bug play'],
  ['building', 'building empresa predio'],
  ['building-2', 'building 2'],
  ['building-complex', 'building complex'],
  ['building-complex-plus', 'building complex plus'],
  ['bus', 'bus'],
  ['bus-front', 'bus front'],
  ['cable', 'cable'],
  ['cable-car', 'cable car'],
  ['cake', 'cake'],
  ['cake-slice', 'cake slice'],
  ['calculator', 'calculator calculadora financeiro contabil calculo'],
  ['calendar', 'calendar calendario agenda data prazo'],
  ['calendar-1', 'calendar 1'],
  ['calendar-arrow-down', 'calendar arrow down'],
  ['calendar-arrow-up', 'calendar arrow up'],
  ['calendar-check', 'calendar check'],
  ['calendar-check-2', 'calendar check 2'],
  ['calendar-chevrons-right', 'calendar chevrons right'],
  ['calendar-clock', 'calendar clock'],
  ['calendar-cog', 'calendar cog'],
  ['calendar-days', 'calendar days'],
  ['calendar-fold', 'calendar fold'],
  ['calendar-heart', 'calendar heart'],
  ['calendar-minus', 'calendar minus'],
  ['calendar-minus-2', 'calendar minus 2'],
  ['calendar-off', 'calendar off'],
  ['calendar-plus', 'calendar plus'],
  ['calendar-plus-2', 'calendar plus 2'],
  ['calendar-range', 'calendar range'],
  ['calendar-search', 'calendar search'],
  ['calendar-sync', 'calendar sync'],
  ['calendar-x', 'calendar x'],
  ['calendar-x-2', 'calendar x 2'],
  ['calendars', 'calendars'],
  ['camera', 'camera camera foto imagem'],
  ['camera-off', 'camera off'],
  ['can', 'can'],
  ['can-soda', 'can soda'],
  ['candlestick-chart', 'candlestick chart'],
  ['candy', 'candy'],
  ['candy-cane', 'candy cane'],
  ['candy-off', 'candy off'],
  ['cannabis', 'cannabis'],
  ['cannabis-off', 'cannabis off'],
  ['captions', 'captions'],
  ['captions-off', 'captions off'],
  ['car', 'car carro veiculo frota'],
  ['car-battery', 'car battery'],
  ['car-front', 'car front'],
  ['car-taxi-front', 'car taxi front'],
  ['caravan', 'caravan'],
  ['card-sim', 'card sim'],
  ['carrot', 'carrot'],
  ['carton', 'carton'],
  ['carton-off', 'carton off'],
  ['case-lower', 'case lower'],
  ['case-sensitive', 'case sensitive'],
  ['case-upper', 'case upper'],
  ['cassette-tape', 'cassette tape'],
  ['cast', 'cast'],
  ['castle', 'castle'],
  ['cat', 'cat'],
  ['cctv', 'cctv'],
  ['cctv-off', 'cctv off'],
  ['chart-area', 'chart area'],
  ['chart-bar', 'chart bar'],
  ['chart-bar-big', 'chart bar big'],
  ['chart-bar-decreasing', 'chart bar decreasing'],
  ['chart-bar-increasing', 'chart bar increasing'],
  ['chart-bar-stacked', 'chart bar stacked'],
  ['chart-candlestick', 'chart candlestick'],
  ['chart-column', 'chart column grafico barras relatorio'],
  ['chart-column-big', 'chart column big'],
  ['chart-column-decreasing', 'chart column decreasing'],
  ['chart-column-increasing', 'chart column increasing'],
  ['chart-column-stacked', 'chart column stacked'],
  ['chart-gantt', 'chart gantt'],
  ['chart-line', 'chart line grafico resultado indicador crescimento'],
  ['chart-network', 'chart network'],
  ['chart-no-axes-column', 'chart no axes column'],
  ['chart-no-axes-column-decreasing', 'chart no axes column decreasing'],
  ['chart-no-axes-column-increasing', 'chart no axes column increasing'],
  ['chart-no-axes-combined', 'chart no axes combined'],
  ['chart-no-axes-gantt', 'chart no axes gantt'],
  ['chart-pie', 'chart pie'],
  ['chart-scatter', 'chart scatter'],
  ['chart-spline', 'chart spline'],
  ['check', 'check'],
  ['check-check', 'check check'],
  ['check-circle', 'check circle'],
  ['check-circle-2', 'check circle 2'],
  ['check-line', 'check line'],
  ['check-square', 'check square'],
  ['check-square-2', 'check square 2'],
  ['chef-hat', 'chef hat'],
  ['cherry', 'cherry'],
  ['chess-bishop', 'chess bishop'],
  ['chess-king', 'chess king'],
  ['chess-knight', 'chess knight'],
  ['chess-pawn', 'chess pawn'],
  ['chess-queen', 'chess queen'],
  ['chess-rook', 'chess rook'],
  ['chevron-down', 'chevron down'],
  ['chevron-down-circle', 'chevron down circle'],
  ['chevron-down-square', 'chevron down square'],
  ['chevron-first', 'chevron first'],
  ['chevron-last', 'chevron last'],
  ['chevron-left', 'chevron left'],
  ['chevron-left-circle', 'chevron left circle'],
  ['chevron-left-square', 'chevron left square'],
  ['chevron-right', 'chevron right'],
  ['chevron-right-circle', 'chevron right circle'],
  ['chevron-right-square', 'chevron right square'],
  ['chevron-up', 'chevron up'],
  ['chevron-up-circle', 'chevron up circle'],
  ['chevron-up-square', 'chevron up square'],
  ['chevrons-down', 'chevrons down'],
  ['chevrons-down-up', 'chevrons down up'],
  ['chevrons-left', 'chevrons left'],
  ['chevrons-left-right', 'chevrons left right'],
  ['chevrons-left-right-ellipsis', 'chevrons left right ellipsis'],
  ['chevrons-right', 'chevrons right'],
  ['chevrons-right-left', 'chevrons right left'],
  ['chevrons-up', 'chevrons up'],
  ['chevrons-up-down', 'chevrons up down'],
  ['chrome', 'chrome'],
  ['chromium', 'chromium'],
  ['church', 'church'],
  ['cigarette', 'cigarette'],
  ['cigarette-off', 'cigarette off'],
  ['circle', 'circle'],
  ['circle-alert', 'circle alert'],
  ['circle-arrow-down', 'circle arrow down'],
  ['circle-arrow-left', 'circle arrow left'],
  ['circle-arrow-out-down-left', 'circle arrow out down left'],
  ['circle-arrow-out-down-right', 'circle arrow out down right'],
  ['circle-arrow-out-up-left', 'circle arrow out up left'],
  ['circle-arrow-out-up-right', 'circle arrow out up right'],
  ['circle-arrow-right', 'circle arrow right'],
  ['circle-arrow-up', 'circle arrow up'],
  ['circle-check', 'circle check'],
  ['circle-check-big', 'circle check big'],
  ['circle-chevron-down', 'circle chevron down'],
  ['circle-chevron-left', 'circle chevron left'],
  ['circle-chevron-right', 'circle chevron right'],
  ['circle-chevron-up', 'circle chevron up'],
  ['circle-dashed', 'circle dashed'],
  ['circle-dashed-check', 'circle dashed check'],
  ['circle-divide', 'circle divide'],
  ['circle-dollar-sign', 'circle dollar sign'],
  ['circle-dot', 'circle dot'],
  ['circle-dot-dashed', 'circle dot dashed'],
  ['circle-ellipsis', 'circle ellipsis'],
  ['circle-equal', 'circle equal'],
  ['circle-euro', 'circle euro'],
  ['circle-fading-arrow-up', 'circle fading arrow up'],
  ['circle-fading-plus', 'circle fading plus'],
  ['circle-gauge', 'circle gauge'],
  ['circle-help', 'circle help'],
  ['circle-minus', 'circle minus'],
  ['circle-off', 'circle off'],
  ['circle-parking', 'circle parking'],
  ['circle-parking-off', 'circle parking off'],
  ['circle-pause', 'circle pause'],
  ['circle-percent', 'circle percent'],
  ['circle-pile', 'circle pile'],
  ['circle-play', 'circle play'],
  ['circle-plus', 'circle plus'],
  ['circle-pound-sterling', 'circle pound sterling'],
  ['circle-power', 'circle power'],
  ['circle-question-mark', 'circle question mark'],
  ['circle-slash', 'circle slash'],
  ['circle-slash-2', 'circle slash 2'],
  ['circle-slashed', 'circle slashed'],
  ['circle-small', 'circle small'],
  ['circle-star', 'circle star'],
  ['circle-stop', 'circle stop'],
  ['circle-user', 'circle user'],
  ['circle-user-round', 'circle user round'],
  ['circle-x', 'circle x'],
  ['circuit-board', 'circuit board'],
  ['citrus', 'citrus'],
  ['clapperboard', 'clapperboard'],
  ['clef-alto', 'clef alto'],
  ['clef-bass', 'clef bass'],
  ['clef-treble', 'clef treble'],
  ['clipboard', 'clipboard'],
  ['clipboard-check', 'clipboard check'],
  ['clipboard-clock', 'clipboard clock'],
  ['clipboard-copy', 'clipboard copy'],
  ['clipboard-edit', 'clipboard edit'],
  ['clipboard-list', 'clipboard list'],
  ['clipboard-minus', 'clipboard minus'],
  ['clipboard-paste', 'clipboard paste'],
  ['clipboard-pen', 'clipboard pen'],
  ['clipboard-pen-line', 'clipboard pen line'],
  ['clipboard-plus', 'clipboard plus'],
  ['clipboard-signature', 'clipboard signature'],
  ['clipboard-type', 'clipboard type'],
  ['clipboard-x', 'clipboard x'],
  ['clock', 'clock relogio hora tempo prazo'],
  ['clock-1', 'clock 1'],
  ['clock-10', 'clock 10'],
  ['clock-11', 'clock 11'],
  ['clock-12', 'clock 12'],
  ['clock-2', 'clock 2'],
  ['clock-3', 'clock 3'],
  ['clock-4', 'clock 4'],
  ['clock-5', 'clock 5'],
  ['clock-6', 'clock 6'],
  ['clock-7', 'clock 7'],
  ['clock-8', 'clock 8'],
  ['clock-9', 'clock 9'],
  ['clock-alert', 'clock alert'],
  ['clock-arrow-down', 'clock arrow down'],
  ['clock-arrow-left', 'clock arrow left'],
  ['clock-arrow-right', 'clock arrow right'],
  ['clock-arrow-up', 'clock arrow up'],
  ['clock-check', 'clock check'],
  ['clock-fading', 'clock fading'],
  ['clock-plus', 'clock plus'],
  ['closed-caption', 'closed caption'],
  ['cloud', 'cloud nuvem cloud armazenamento'],
  ['cloud-alert', 'cloud alert'],
  ['cloud-backup', 'cloud backup'],
  ['cloud-check', 'cloud check'],
  ['cloud-cog', 'cloud cog'],
  ['cloud-download', 'cloud download'],
  ['cloud-drizzle', 'cloud drizzle'],
  ['cloud-fog', 'cloud fog'],
  ['cloud-hail', 'cloud hail'],
  ['cloud-lightning', 'cloud lightning'],
  ['cloud-moon', 'cloud moon'],
  ['cloud-moon-rain', 'cloud moon rain'],
  ['cloud-off', 'cloud off'],
  ['cloud-rain', 'cloud rain'],
  ['cloud-rain-wind', 'cloud rain wind'],
  ['cloud-snow', 'cloud snow'],
  ['cloud-sun', 'cloud sun'],
  ['cloud-sun-rain', 'cloud sun rain'],
  ['cloud-sync', 'cloud sync'],
  ['cloud-upload', 'cloud upload'],
  ['cloudy', 'cloudy'],
  ['clover', 'clover'],
  ['club', 'club'],
  ['code', 'code codigo desenvolvimento programacao'],
  ['code-2', 'code 2'],
  ['code-square', 'code square'],
  ['code-xml', 'code xml'],
  ['codepen', 'codepen'],
  ['codesandbox', 'codesandbox'],
  ['coffee', 'coffee'],
  ['cog', 'cog'],
  ['coins', 'coins'],
  ['columns', 'columns'],
  ['columns-2', 'columns 2'],
  ['columns-3', 'columns 3'],
  ['columns-3-cog', 'columns 3 cog'],
  ['columns-4', 'columns 4'],
  ['columns-settings', 'columns settings'],
  ['combine', 'combine'],
  ['command', 'command'],
  ['compass', 'compass'],
  ['component', 'component'],
  ['computer', 'computer'],
  ['concierge-bell', 'concierge bell'],
  ['cone', 'cone'],
  ['construction', 'construction'],
  ['contact', 'contact'],
  ['contact-2', 'contact 2'],
  ['contact-round', 'contact round'],
  ['container', 'container'],
  ['contrast', 'contrast'],
  ['cookie', 'cookie'],
  ['cooking-pot', 'cooking pot'],
  ['copy', 'copy'],
  ['copy-check', 'copy check'],
  ['copy-minus', 'copy minus'],
  ['copy-plus', 'copy plus'],
  ['copy-slash', 'copy slash'],
  ['copy-x', 'copy x'],
  ['copyleft', 'copyleft'],
  ['copyright', 'copyright'],
  ['corner-down-left', 'corner down left'],
  ['corner-down-right', 'corner down right'],
  ['corner-left-down', 'corner left down'],
  ['corner-left-up', 'corner left up'],
  ['corner-right-down', 'corner right down'],
  ['corner-right-up', 'corner right up'],
  ['corner-up-left', 'corner up left'],
  ['corner-up-right', 'corner up right'],
  ['cpu', 'cpu'],
  ['creative-commons', 'creative commons'],
  ['credit-card', 'credit card'],
  ['credit-card-check', 'credit card check'],
  ['credit-card-minus', 'credit card minus'],
  ['credit-card-plus', 'credit card plus'],
  ['credit-card-reader', 'credit card reader'],
  ['credit-card-x', 'credit card x'],
  ['croissant', 'croissant'],
  ['crop', 'crop'],
  ['cross', 'cross saude hospital clinica medico'],
  ['crosshair', 'crosshair'],
  ['crown', 'crown'],
  ['cuboid', 'cuboid'],
  ['cup-soda', 'cup soda'],
  ['curly-braces', 'curly braces'],
  ['currency', 'currency'],
  ['cylinder', 'cylinder'],
  ['dam', 'dam'],
  ['database', 'database banco de dados base'],
  ['database-arrow-down', 'database arrow down'],
  ['database-arrow-up', 'database arrow up'],
  ['database-backup', 'database backup'],
  ['database-check', 'database check'],
  ['database-minus', 'database minus'],
  ['database-plus', 'database plus'],
  ['database-search', 'database search'],
  ['database-x', 'database x'],
  ['database-zap', 'database zap'],
  ['decimals-arrow-left', 'decimals arrow left'],
  ['decimals-arrow-right', 'decimals arrow right'],
  ['delete', 'delete'],
  ['dessert', 'dessert'],
  ['diameter', 'diameter'],
  ['diamond', 'diamond'],
  ['diamond-minus', 'diamond minus'],
  ['diamond-percent', 'diamond percent'],
  ['diamond-plus', 'diamond plus'],
  ['dice-1', 'dice 1'],
  ['dice-2', 'dice 2'],
  ['dice-3', 'dice 3'],
  ['dice-4', 'dice 4'],
  ['dice-5', 'dice 5'],
  ['dice-6', 'dice 6'],
  ['dices', 'dices'],
  ['diff', 'diff'],
  ['disc', 'disc'],
  ['disc-2', 'disc 2'],
  ['disc-3', 'disc 3'],
  ['disc-album', 'disc album'],
  ['divide', 'divide'],
  ['divide-circle', 'divide circle'],
  ['divide-square', 'divide square'],
  ['dna', 'dna'],
  ['dna-off', 'dna off'],
  ['dock', 'dock'],
  ['dog', 'dog'],
  ['dollar-sign', 'dollar sign'],
  ['dome', 'dome'],
  ['donut', 'donut'],
  ['door-closed', 'door closed'],
  ['door-closed-locked', 'door closed locked'],
  ['door-open', 'door open'],
  ['door-stairwell', 'door stairwell'],
  ['dot', 'dot'],
  ['dot-square', 'dot square'],
  ['download', 'download'],
  ['download-cloud', 'download cloud'],
  ['drafting-compass', 'drafting compass'],
  ['drama', 'drama'],
  ['dribbble', 'dribbble'],
  ['drill', 'drill'],
  ['drone', 'drone'],
  ['droplet', 'droplet'],
  ['droplet-off', 'droplet off'],
  ['droplets', 'droplets'],
  ['drum', 'drum'],
  ['drumstick', 'drumstick'],
  ['dumbbell', 'dumbbell'],
  ['ear', 'ear'],
  ['ear-off', 'ear off'],
  ['earth', 'earth'],
  ['earth-lock', 'earth lock'],
  ['eclipse', 'eclipse'],
  ['edit', 'edit'],
  ['edit-2', 'edit 2'],
  ['edit-3', 'edit 3'],
  ['egg', 'egg'],
  ['egg-fried', 'egg fried'],
  ['egg-off', 'egg off'],
  ['eject', 'eject'],
  ['ellipse', 'ellipse'],
  ['ellipsis', 'ellipsis'],
  ['ellipsis-vertical', 'ellipsis vertical'],
  ['engine', 'engine'],
  ['equal', 'equal'],
  ['equal-approximately', 'equal approximately'],
  ['equal-approximately-not', 'equal approximately not'],
  ['equal-not', 'equal not'],
  ['equal-square', 'equal square'],
  ['eraser', 'eraser'],
  ['ethernet-port', 'ethernet port'],
  ['euro', 'euro'],
  ['ev-charger', 'ev charger'],
  ['expand', 'expand'],
  ['external-link', 'external link'],
  ['eye', 'eye'],
  ['eye-closed', 'eye closed'],
  ['eye-dashed', 'eye dashed'],
  ['eye-off', 'eye off'],
  ['face-angry', 'face angry'],
  ['face-expressionless', 'face expressionless'],
  ['face-grinning', 'face grinning'],
  ['face-neutral', 'face neutral'],
  ['face-slightly-frowning', 'face slightly frowning'],
  ['face-slightly-smiling', 'face slightly smiling'],
  ['face-slightly-smiling-plus', 'face slightly smiling plus'],
  ['facebook', 'facebook'],
  ['factory', 'factory fabrica producao industria'],
  ['fan', 'fan'],
  ['fast-forward', 'fast forward'],
  ['feather', 'feather'],
  ['fence', 'fence'],
  ['ferris-wheel', 'ferris wheel'],
  ['figma', 'figma'],
  ['file', 'file'],
  ['file-archive', 'file archive'],
  ['file-audio', 'file audio'],
  ['file-audio-2', 'file audio 2'],
  ['file-axis-3-d', 'file axis 3 d'],
  ['file-axis-3d', 'file axis 3d'],
  ['file-badge', 'file badge'],
  ['file-badge-2', 'file badge 2'],
  ['file-bar-chart', 'file bar chart'],
  ['file-bar-chart-2', 'file bar chart 2'],
  ['file-box', 'file box'],
  ['file-braces', 'file braces'],
  ['file-braces-corner', 'file braces corner'],
  ['file-chart-column', 'file chart column'],
  ['file-chart-column-increasing', 'file chart column increasing'],
  ['file-chart-line', 'file chart line'],
  ['file-chart-pie', 'file chart pie'],
  ['file-check', 'file check certidao documento aprovado'],
  ['file-check-2', 'file check 2'],
  ['file-check-corner', 'file check corner'],
  ['file-clock', 'file clock'],
  ['file-code', 'file code'],
  ['file-code-2', 'file code 2'],
  ['file-code-corner', 'file code corner'],
  ['file-cog', 'file cog'],
  ['file-cog-2', 'file cog 2'],
  ['file-diff', 'file diff'],
  ['file-digit', 'file digit'],
  ['file-down', 'file down'],
  ['file-edit', 'file edit'],
  ['file-exclamation-point', 'file exclamation point'],
  ['file-headphone', 'file headphone'],
  ['file-heart', 'file heart'],
  ['file-image', 'file image'],
  ['file-input', 'file input'],
  ['file-json', 'file json'],
  ['file-json-2', 'file json 2'],
  ['file-key', 'file key'],
  ['file-key-2', 'file key 2'],
  ['file-line-chart', 'file line chart'],
  ['file-lock', 'file lock'],
  ['file-lock-2', 'file lock 2'],
  ['file-minus', 'file minus'],
  ['file-minus-2', 'file minus 2'],
  ['file-minus-corner', 'file minus corner'],
  ['file-music', 'file music'],
  ['file-output', 'file output'],
  ['file-pen', 'file pen'],
  ['file-pen-line', 'file pen line'],
  ['file-pie-chart', 'file pie chart'],
  ['file-play', 'file play'],
  ['file-plus', 'file plus'],
  ['file-plus-2', 'file plus 2'],
  ['file-plus-corner', 'file plus corner'],
  ['file-question', 'file question'],
  ['file-question-mark', 'file question mark'],
  ['file-scan', 'file scan'],
  ['file-search', 'file search'],
  ['file-search-2', 'file search 2'],
  ['file-search-corner', 'file search corner'],
  ['file-signal', 'file signal'],
  ['file-signature', 'file signature'],
  ['file-sliders', 'file sliders'],
  ['file-spreadsheet', 'file spreadsheet'],
  ['file-stack', 'file stack'],
  ['file-symlink', 'file symlink'],
  ['file-terminal', 'file terminal'],
  ['file-text', 'file text documento arquivo texto papel'],
  ['file-type', 'file type'],
  ['file-type-2', 'file type 2'],
  ['file-type-corner', 'file type corner'],
  ['file-up', 'file up'],
  ['file-user', 'file user'],
  ['file-video', 'file video'],
  ['file-video-2', 'file video 2'],
  ['file-video-camera', 'file video camera'],
  ['file-volume', 'file volume'],
  ['file-volume-2', 'file volume 2'],
  ['file-warning', 'file warning'],
  ['file-x', 'file x'],
  ['file-x-2', 'file x 2'],
  ['file-x-corner', 'file x corner'],
  ['files', 'files'],
  ['film', 'film'],
  ['filter', 'filter filtro funil'],
  ['filter-x', 'filter x'],
  ['fingerprint', 'fingerprint'],
  ['fingerprint-pattern', 'fingerprint pattern'],
  ['fire-extinguisher', 'fire extinguisher'],
  ['fish', 'fish'],
  ['fish-off', 'fish off'],
  ['fish-symbol', 'fish symbol'],
  ['fishing-hook', 'fishing hook'],
  ['fishing-rod', 'fishing rod'],
  ['flag', 'flag bandeira marcador prioridade'],
  ['flag-off', 'flag off'],
  ['flag-triangle-left', 'flag triangle left'],
  ['flag-triangle-right', 'flag triangle right'],
  ['flame', 'flame'],
  ['flame-kindling', 'flame kindling'],
  ['flashlight', 'flashlight'],
  ['flashlight-off', 'flashlight off'],
  ['flask-conical', 'flask conical'],
  ['flask-conical-off', 'flask conical off'],
  ['flask-round', 'flask round'],
  ['flip-horizontal', 'flip horizontal'],
  ['flip-horizontal-2', 'flip horizontal 2'],
  ['flip-vertical', 'flip vertical'],
  ['flip-vertical-2', 'flip vertical 2'],
  ['flower', 'flower'],
  ['flower-2', 'flower 2'],
  ['focus', 'focus'],
  ['fold-horizontal', 'fold horizontal'],
  ['fold-vertical', 'fold vertical'],
  ['folder', 'folder pasta arquivo diretorio'],
  ['folder-archive', 'folder archive'],
  ['folder-bookmark', 'folder bookmark'],
  ['folder-check', 'folder check'],
  ['folder-clock', 'folder clock'],
  ['folder-closed', 'folder closed'],
  ['folder-code', 'folder code'],
  ['folder-cog', 'folder cog'],
  ['folder-cog-2', 'folder cog 2'],
  ['folder-dot', 'folder dot'],
  ['folder-down', 'folder down'],
  ['folder-edit', 'folder edit'],
  ['folder-git', 'folder git'],
  ['folder-git-2', 'folder git 2'],
  ['folder-heart', 'folder heart'],
  ['folder-input', 'folder input'],
  ['folder-kanban', 'folder kanban'],
  ['folder-key', 'folder key'],
  ['folder-lock', 'folder lock'],
  ['folder-minus', 'folder minus'],
  ['folder-open', 'folder open'],
  ['folder-open-dot', 'folder open dot'],
  ['folder-output', 'folder output'],
  ['folder-pen', 'folder pen'],
  ['folder-plus', 'folder plus'],
  ['folder-root', 'folder root'],
  ['folder-search', 'folder search'],
  ['folder-search-2', 'folder search 2'],
  ['folder-symlink', 'folder symlink'],
  ['folder-sync', 'folder sync'],
  ['folder-tree', 'folder tree'],
  ['folder-up', 'folder up'],
  ['folder-x', 'folder x'],
  ['folders', 'folders'],
  ['footprints', 'footprints'],
  ['fork-knife', 'fork knife'],
  ['fork-knife-crossed', 'fork knife crossed'],
  ['forklift', 'forklift'],
  ['form', 'form'],
  ['form-input', 'form input'],
  ['forward', 'forward'],
  ['frame', 'frame'],
  ['framer', 'framer'],
  ['frown', 'frown'],
  ['fuel', 'fuel'],
  ['fullscreen', 'fullscreen'],
  ['function-square', 'function square'],
  ['funnel', 'funnel'],
  ['funnel-plus', 'funnel plus'],
  ['funnel-x', 'funnel x'],
  ['galaxy', 'galaxy'],
  ['gallery-horizontal', 'gallery horizontal'],
  ['gallery-horizontal-end', 'gallery horizontal end'],
  ['gallery-thumbnails', 'gallery thumbnails'],
  ['gallery-vertical', 'gallery vertical'],
  ['gallery-vertical-end', 'gallery vertical end'],
  ['gamepad', 'gamepad'],
  ['gamepad-2', 'gamepad 2'],
  ['gamepad-directional', 'gamepad directional'],
  ['gantt-chart', 'gantt chart'],
  ['gantt-chart-square', 'gantt chart square'],
  ['gap-horizontal', 'gap horizontal'],
  ['gap-vertical', 'gap vertical'],
  ['gauge', 'gauge'],
  ['gauge-circle', 'gauge circle'],
  ['gavel', 'gavel martelo juiz juridico tribunal'],
  ['gem', 'gem'],
  ['georgian-lari', 'georgian lari'],
  ['germ', 'germ'],
  ['germ-off', 'germ off'],
  ['ghost', 'ghost'],
  ['gift', 'gift'],
  ['git-branch', 'git branch ramificacao versao fluxo'],
  ['git-branch-minus', 'git branch minus'],
  ['git-branch-plus', 'git branch plus'],
  ['git-commit', 'git commit'],
  ['git-commit-horizontal', 'git commit horizontal'],
  ['git-commit-vertical', 'git commit vertical'],
  ['git-compare', 'git compare'],
  ['git-compare-arrows', 'git compare arrows'],
  ['git-fork', 'git fork'],
  ['git-graph', 'git graph'],
  ['git-merge', 'git merge'],
  ['git-merge-conflict', 'git merge conflict'],
  ['git-pull-request', 'git pull request'],
  ['git-pull-request-arrow', 'git pull request arrow'],
  ['git-pull-request-closed', 'git pull request closed'],
  ['git-pull-request-create', 'git pull request create'],
  ['git-pull-request-create-arrow', 'git pull request create arrow'],
  ['git-pull-request-draft', 'git pull request draft'],
  ['github', 'github'],
  ['gitlab', 'gitlab'],
  ['glass-water', 'glass water'],
  ['glasses', 'glasses'],
  ['globe', 'globe'],
  ['globe-2', 'globe 2'],
  ['globe-check', 'globe check'],
  ['globe-code', 'globe code'],
  ['globe-lock', 'globe lock'],
  ['globe-off', 'globe off'],
  ['globe-x', 'globe x'],
  ['goal', 'goal'],
  ['gpu', 'gpu'],
  ['grab', 'grab'],
  ['graduation-cap', 'graduation cap educacao formacao treinamento escola'],
  ['grape', 'grape'],
  ['grid', 'grid'],
  ['grid-2-x-2', 'grid 2 x 2'],
  ['grid-2-x-2-check', 'grid 2 x 2 check'],
  ['grid-2-x-2-plus', 'grid 2 x 2 plus'],
  ['grid-2-x-2-x', 'grid 2 x 2 x'],
  ['grid-2x2', 'grid 2x2'],
  ['grid-2x2-check', 'grid 2x2 check'],
  ['grid-2x2-plus', 'grid 2x2 plus'],
  ['grid-2x2-x', 'grid 2x2 x'],
  ['grid-3-x-3', 'grid 3 x 3'],
  ['grid-3x2', 'grid 3x2'],
  ['grid-3x3', 'grid 3x3'],
  ['grip', 'grip'],
  ['grip-horizontal', 'grip horizontal'],
  ['grip-vertical', 'grip vertical'],
  ['group', 'group'],
  ['guitar', 'guitar'],
  ['ham', 'ham'],
  ['hamburger', 'hamburger'],
  ['hammer', 'hammer'],
  ['hand', 'hand'],
  ['hand-coins', 'hand coins'],
  ['hand-fist', 'hand fist'],
  ['hand-grab', 'hand grab'],
  ['hand-heart', 'hand heart'],
  ['hand-helping', 'hand helping'],
  ['hand-metal', 'hand metal'],
  ['hand-platter', 'hand platter'],
  ['handbag', 'handbag'],
  ['handshake', 'handshake'],
  ['hard-drive', 'hard drive'],
  ['hard-drive-download', 'hard drive download'],
  ['hard-drive-upload', 'hard drive upload'],
  ['hard-hat', 'hard hat'],
  ['hash', 'hash'],
  ['hat-glasses', 'hat glasses'],
  ['haze', 'haze'],
  ['hd', 'hd'],
  ['hdmi-port', 'hdmi port'],
  ['heading', 'heading'],
  ['heading-1', 'heading 1'],
  ['heading-2', 'heading 2'],
  ['heading-3', 'heading 3'],
  ['heading-4', 'heading 4'],
  ['heading-5', 'heading 5'],
  ['heading-6', 'heading 6'],
  ['headphone-off', 'headphone off'],
  ['headphones', 'headphones'],
  ['headset', 'headset'],
  ['heart', 'heart'],
  ['heart-crack', 'heart crack'],
  ['heart-handshake', 'heart handshake beneficios acordo parceria'],
  ['heart-minus', 'heart minus'],
  ['heart-off', 'heart off'],
  ['heart-plus', 'heart plus'],
  ['heart-pulse', 'heart pulse'],
  ['heart-x', 'heart x'],
  ['heater', 'heater'],
  ['helicopter', 'helicopter'],
  ['help-circle', 'help circle'],
  ['helping-hand', 'helping hand'],
  ['hexagon', 'hexagon'],
  ['highlighter', 'highlighter'],
  ['history', 'history'],
  ['home', 'home'],
  ['hop', 'hop'],
  ['hop-off', 'hop off'],
  ['hospital', 'hospital'],
  ['hotel', 'hotel'],
  ['hourglass', 'hourglass'],
  ['hourglass-cog', 'hourglass cog'],
  ['house', 'house'],
  ['house-heart', 'house heart'],
  ['house-plug', 'house plug'],
  ['house-plus', 'house plus'],
  ['house-wifi', 'house wifi'],
  ['houses', 'houses'],
  ['ice-cream', 'ice cream'],
  ['ice-cream-2', 'ice cream 2'],
  ['ice-cream-bowl', 'ice cream bowl'],
  ['ice-cream-cone', 'ice cream cone'],
  ['id-card', 'id card cracha identidade documento'],
  ['id-card-lanyard', 'id card lanyard'],
  ['image', 'image'],
  ['image-down', 'image down'],
  ['image-minus', 'image minus'],
  ['image-off', 'image off'],
  ['image-play', 'image play'],
  ['image-plus', 'image plus'],
  ['image-up', 'image up'],
  ['image-upscale', 'image upscale'],
  ['images', 'images'],
  ['import', 'import'],
  ['inbox', 'inbox'],
  ['indent', 'indent'],
  ['indent-decrease', 'indent decrease'],
  ['indent-increase', 'indent increase'],
  ['indian-rupee', 'indian rupee'],
  ['infinity', 'infinity'],
  ['info', 'info'],
  ['inspect', 'inspect'],
  ['inspection-panel', 'inspection panel'],
  ['instagram', 'instagram'],
  ['italic', 'italic'],
  ['iteration-ccw', 'iteration ccw'],
  ['iteration-cw', 'iteration cw'],
  ['iv-bag', 'iv bag'],
  ['japanese-yen', 'japanese yen'],
  ['jersey-pound', 'jersey pound'],
  ['joystick', 'joystick'],
  ['kanban', 'kanban'],
  ['kanban-square', 'kanban square'],
  ['kanban-square-dashed', 'kanban square dashed'],
  ['kayak', 'kayak'],
  ['key', 'key chave acesso senha'],
  ['key-round', 'key round'],
  ['key-square', 'key square'],
  ['keyboard', 'keyboard'],
  ['keyboard-music', 'keyboard music'],
  ['keyboard-off', 'keyboard off'],
  ['lamp', 'lamp'],
  ['lamp-ceiling', 'lamp ceiling'],
  ['lamp-desk', 'lamp desk'],
  ['lamp-floor', 'lamp floor'],
  ['lamp-wall-down', 'lamp wall down'],
  ['lamp-wall-up', 'lamp wall up'],
  ['land-plot', 'land plot'],
  ['landmark', 'landmark'],
  ['languages', 'languages'],
  ['laptop', 'laptop'],
  ['laptop-2', 'laptop 2'],
  ['laptop-minimal', 'laptop minimal'],
  ['laptop-minimal-check', 'laptop minimal check'],
  ['lasso', 'lasso'],
  ['lasso-select', 'lasso select'],
  ['laugh', 'laugh'],
  ['layer-arrow-down', 'layer arrow down'],
  ['layer-arrow-up', 'layer arrow up'],
  ['layers', 'layers'],
  ['layers-2', 'layers 2'],
  ['layers-3', 'layers 3'],
  ['layers-arrow-down', 'layers arrow down'],
  ['layers-arrow-up', 'layers arrow up'],
  ['layers-minus', 'layers minus'],
  ['layers-plus', 'layers plus'],
  ['layout', 'layout'],
  ['layout-arrow-down', 'layout arrow down'],
  ['layout-arrow-right', 'layout arrow right'],
  ['layout-dashboard', 'layout dashboard'],
  ['layout-freeform', 'layout freeform'],
  ['layout-grid', 'layout grid'],
  ['layout-list', 'layout list'],
  ['layout-panel-left', 'layout panel left'],
  ['layout-panel-top', 'layout panel top'],
  ['layout-template', 'layout template'],
  ['leaf', 'leaf folha sustentabilidade meio ambiente'],
  ['leafy-green', 'leafy green'],
  ['lectern', 'lectern'],
  ['lens-concave', 'lens concave'],
  ['lens-convex', 'lens convex'],
  ['letter-text', 'letter text'],
  ['library', 'library'],
  ['library-big', 'library big'],
  ['library-square', 'library square'],
  ['life-buoy', 'life buoy suporte ajuda chamado socorro atendimento'],
  ['ligature', 'ligature'],
  ['lightbulb', 'lightbulb'],
  ['lightbulb-off', 'lightbulb off'],
  ['lighthouse', 'lighthouse'],
  ['line-chart', 'line chart'],
  ['line-dot-right-horizontal', 'line dot right horizontal'],
  ['line-squiggle', 'line squiggle'],
  ['line-style', 'line style'],
  ['link', 'link'],
  ['link-2', 'link 2'],
  ['link-2-off', 'link 2 off'],
  ['linkedin', 'linkedin'],
  ['list', 'list'],
  ['list-check', 'list check'],
  ['list-checks', 'list checks'],
  ['list-chevrons-down-up', 'list chevrons down up'],
  ['list-chevrons-up-down', 'list chevrons up down'],
  ['list-clock', 'list clock'],
  ['list-collapse', 'list collapse'],
  ['list-end', 'list end'],
  ['list-filter', 'list filter'],
  ['list-filter-plus', 'list filter plus'],
  ['list-indent-decrease', 'list indent decrease'],
  ['list-indent-increase', 'list indent increase'],
  ['list-minus', 'list minus'],
  ['list-music', 'list music'],
  ['list-ordered', 'list ordered'],
  ['list-plus', 'list plus'],
  ['list-restart', 'list restart'],
  ['list-sort-ascending', 'list sort ascending'],
  ['list-sort-descending', 'list sort descending'],
  ['list-start', 'list start'],
  ['list-todo', 'list todo'],
  ['list-tree', 'list tree'],
  ['list-video', 'list video'],
  ['list-x', 'list x'],
  ['loader', 'loader'],
  ['loader-2', 'loader 2'],
  ['loader-circle', 'loader circle'],
  ['loader-pinwheel', 'loader pinwheel'],
  ['locate', 'locate'],
  ['locate-fixed', 'locate fixed'],
  ['locate-off', 'locate off'],
  ['location-edit', 'location edit'],
  ['lock', 'lock cadeado seguranca bloqueio privado'],
  ['lock-keyhole', 'lock keyhole'],
  ['lock-keyhole-open', 'lock keyhole open'],
  ['lock-open', 'lock open'],
  ['log-in', 'log in'],
  ['log-out', 'log out'],
  ['logs', 'logs'],
  ['lollipop', 'lollipop'],
  ['luggage', 'luggage'],
  ['m-square', 'm square'],
  ['magnet', 'magnet'],
  ['mail', 'mail email correio mensagem'],
  ['mail-badge', 'mail badge'],
  ['mail-check', 'mail check'],
  ['mail-clock', 'mail clock'],
  ['mail-minus', 'mail minus'],
  ['mail-open', 'mail open'],
  ['mail-pen', 'mail pen'],
  ['mail-plus', 'mail plus'],
  ['mail-question', 'mail question'],
  ['mail-question-mark', 'mail question mark'],
  ['mail-search', 'mail search'],
  ['mail-warning', 'mail warning'],
  ['mail-x', 'mail x'],
  ['mailbox', 'mailbox'],
  ['mails', 'mails'],
  ['map', 'map'],
  ['map-minus', 'map minus'],
  ['map-pin', 'map pin local endereco mapa localizacao'],
  ['map-pin-check', 'map pin check'],
  ['map-pin-check-inside', 'map pin check inside'],
  ['map-pin-house', 'map pin house'],
  ['map-pin-minus', 'map pin minus'],
  ['map-pin-minus-inside', 'map pin minus inside'],
  ['map-pin-off', 'map pin off'],
  ['map-pin-pen', 'map pin pen'],
  ['map-pin-plus', 'map pin plus'],
  ['map-pin-plus-inside', 'map pin plus inside'],
  ['map-pin-search', 'map pin search'],
  ['map-pin-x', 'map pin x'],
  ['map-pin-x-inside', 'map pin x inside'],
  ['map-pinned', 'map pinned'],
  ['map-plus', 'map plus'],
  ['mars', 'mars'],
  ['mars-stroke', 'mars stroke'],
  ['martini', 'martini'],
  ['maximize', 'maximize'],
  ['maximize-2', 'maximize 2'],
  ['medal', 'medal'],
  ['megaphone', 'megaphone comunicacao marketing anuncio'],
  ['megaphone-off', 'megaphone off'],
  ['meh', 'meh'],
  ['memory-stick', 'memory stick'],
  ['menu', 'menu'],
  ['menu-square', 'menu square'],
  ['merge', 'merge'],
  ['message-circle', 'message circle'],
  ['message-circle-check', 'message circle check'],
  ['message-circle-code', 'message circle code'],
  ['message-circle-dashed', 'message circle dashed'],
  ['message-circle-dashed-check', 'message circle dashed check'],
  ['message-circle-heart', 'message circle heart'],
  ['message-circle-more', 'message circle more'],
  ['message-circle-off', 'message circle off'],
  ['message-circle-plus', 'message circle plus'],
  ['message-circle-question', 'message circle question'],
  ['message-circle-question-mark', 'message circle question mark'],
  ['message-circle-reply', 'message circle reply'],
  ['message-circle-warning', 'message circle warning'],
  ['message-circle-x', 'message circle x'],
  ['message-square', 'message square'],
  ['message-square-check', 'message square check'],
  ['message-square-code', 'message square code'],
  ['message-square-dashed', 'message square dashed'],
  ['message-square-diff', 'message square diff'],
  ['message-square-dot', 'message square dot'],
  ['message-square-heart', 'message square heart'],
  ['message-square-lock', 'message square lock'],
  ['message-square-more', 'message square more'],
  ['message-square-off', 'message square off'],
  ['message-square-plus', 'message square plus'],
  ['message-square-quote', 'message square quote'],
  ['message-square-reply', 'message square reply'],
  ['message-square-share', 'message square share'],
  ['message-square-text', 'message square text'],
  ['message-square-warning', 'message square warning'],
  ['message-square-x', 'message square x'],
  ['messages-circle', 'messages circle'],
  ['messages-square', 'messages square'],
  ['metronome', 'metronome'],
  ['mic', 'mic'],
  ['mic-2', 'mic 2'],
  ['mic-audio-lines', 'mic audio lines'],
  ['mic-off', 'mic off'],
  ['mic-signal', 'mic signal'],
  ['mic-vocal', 'mic vocal'],
  ['microchip', 'microchip'],
  ['microscope', 'microscope'],
  ['microwave', 'microwave'],
  ['midi-port', 'midi port'],
  ['milestone', 'milestone'],
  ['milk', 'milk'],
  ['milk-off', 'milk off'],
  ['minimize', 'minimize'],
  ['minimize-2', 'minimize 2'],
  ['minus', 'minus'],
  ['minus-circle', 'minus circle'],
  ['minus-square', 'minus square'],
  ['mirror-rectangular', 'mirror rectangular'],
  ['mirror-round', 'mirror round'],
  ['monitor', 'monitor'],
  ['monitor-check', 'monitor check'],
  ['monitor-cloud', 'monitor cloud'],
  ['monitor-cog', 'monitor cog'],
  ['monitor-dot', 'monitor dot'],
  ['monitor-down', 'monitor down'],
  ['monitor-off', 'monitor off'],
  ['monitor-pause', 'monitor pause'],
  ['monitor-play', 'monitor play'],
  ['monitor-smartphone', 'monitor smartphone'],
  ['monitor-speaker', 'monitor speaker'],
  ['monitor-stop', 'monitor stop'],
  ['monitor-up', 'monitor up'],
  ['monitor-x', 'monitor x'],
  ['moon', 'moon'],
  ['moon-star', 'moon star'],
  ['mop', 'mop'],
  ['mop-sparkles', 'mop sparkles'],
  ['more-horizontal', 'more horizontal'],
  ['more-vertical', 'more vertical'],
  ['mosque', 'mosque'],
  ['motorbike', 'motorbike'],
  ['mountain', 'mountain'],
  ['mountain-snow', 'mountain snow'],
  ['mouse', 'mouse'],
  ['mouse-left', 'mouse left'],
  ['mouse-off', 'mouse off'],
  ['mouse-pointer', 'mouse pointer'],
  ['mouse-pointer-2', 'mouse pointer 2'],
  ['mouse-pointer-2-off', 'mouse pointer 2 off'],
  ['mouse-pointer-ban', 'mouse pointer ban'],
  ['mouse-pointer-click', 'mouse pointer click'],
  ['mouse-pointer-square', 'mouse pointer square'],
  ['mouse-pointer-square-dashed', 'mouse pointer square dashed'],
  ['mouse-right', 'mouse right'],
  ['mouth', 'mouth'],
  ['mouth-off', 'mouth off'],
  ['move', 'move'],
  ['move-3-d', 'move 3 d'],
  ['move-3d', 'move 3d'],
  ['move-diagonal', 'move diagonal'],
  ['move-diagonal-2', 'move diagonal 2'],
  ['move-down', 'move down'],
  ['move-down-left', 'move down left'],
  ['move-down-right', 'move down right'],
  ['move-horizontal', 'move horizontal'],
  ['move-left', 'move left'],
  ['move-right', 'move right'],
  ['move-up', 'move up'],
  ['move-up-left', 'move up left'],
  ['move-up-right', 'move up right'],
  ['move-vertical', 'move vertical'],
  ['music', 'music musica audio som'],
  ['music-2', 'music 2'],
  ['music-3', 'music 3'],
  ['music-4', 'music 4'],
  ['navigation', 'navigation'],
  ['navigation-2', 'navigation 2'],
  ['navigation-2-off', 'navigation 2 off'],
  ['navigation-off', 'navigation off'],
  ['network', 'network'],
  ['newspaper', 'newspaper'],
  ['nfc', 'nfc'],
  ['non-binary', 'non binary'],
  ['notebook', 'notebook'],
  ['notebook-dot', 'notebook dot'],
  ['notebook-pen', 'notebook pen'],
  ['notebook-tabs', 'notebook tabs'],
  ['notebook-text', 'notebook text'],
  ['notepad-text', 'notepad text'],
  ['notepad-text-dashed', 'notepad text dashed'],
  ['nut', 'nut'],
  ['nut-off', 'nut off'],
  ['octagon', 'octagon'],
  ['octagon-alert', 'octagon alert'],
  ['octagon-minus', 'octagon minus'],
  ['octagon-pause', 'octagon pause'],
  ['octagon-x', 'octagon x'],
  ['omega', 'omega'],
  ['option', 'option'],
  ['orbit', 'orbit'],
  ['origami', 'origami'],
  ['outdent', 'outdent'],
  ['package', 'package pacote estoque caixa produto'],
  ['package-2', 'package 2'],
  ['package-check', 'package check'],
  ['package-minus', 'package minus'],
  ['package-open', 'package open'],
  ['package-plus', 'package plus'],
  ['package-search', 'package search'],
  ['package-x', 'package x'],
  ['paint-bucket', 'paint bucket'],
  ['paint-roller', 'paint roller'],
  ['paintbrush', 'paintbrush'],
  ['paintbrush-2', 'paintbrush 2'],
  ['paintbrush-vertical', 'paintbrush vertical'],
  ['palette', 'palette'],
  ['palmtree', 'palmtree'],
  ['panda', 'panda'],
  ['panel-bottom', 'panel bottom'],
  ['panel-bottom-close', 'panel bottom close'],
  ['panel-bottom-dashed', 'panel bottom dashed'],
  ['panel-bottom-inactive', 'panel bottom inactive'],
  ['panel-bottom-open', 'panel bottom open'],
  ['panel-left', 'panel left'],
  ['panel-left-close', 'panel left close'],
  ['panel-left-dashed', 'panel left dashed'],
  ['panel-left-inactive', 'panel left inactive'],
  ['panel-left-open', 'panel left open'],
  ['panel-left-right-dashed', 'panel left right dashed'],
  ['panel-right', 'panel right'],
  ['panel-right-close', 'panel right close'],
  ['panel-right-dashed', 'panel right dashed'],
  ['panel-right-inactive', 'panel right inactive'],
  ['panel-right-open', 'panel right open'],
  ['panel-top', 'panel top'],
  ['panel-top-bottom-dashed', 'panel top bottom dashed'],
  ['panel-top-close', 'panel top close'],
  ['panel-top-dashed', 'panel top dashed'],
  ['panel-top-inactive', 'panel top inactive'],
  ['panel-top-open', 'panel top open'],
  ['panels-left-bottom', 'panels left bottom'],
  ['panels-left-right', 'panels left right'],
  ['panels-right-bottom', 'panels right bottom'],
  ['panels-top-bottom', 'panels top bottom'],
  ['panels-top-left', 'panels top left'],
  ['paper-bag', 'paper bag'],
  ['paperclip', 'paperclip'],
  ['parasol', 'parasol'],
  ['parentheses', 'parentheses'],
  ['park', 'park'],
  ['parking-circle', 'parking circle'],
  ['parking-circle-off', 'parking circle off'],
  ['parking-meter', 'parking meter'],
  ['parking-square', 'parking square'],
  ['parking-square-off', 'parking square off'],
  ['party-popper', 'party popper'],
  ['pause', 'pause'],
  ['pause-circle', 'pause circle'],
  ['pause-octagon', 'pause octagon'],
  ['paw-print', 'paw print'],
  ['pc-case', 'pc case'],
  ['pen', 'pen'],
  ['pen-box', 'pen box'],
  ['pen-line', 'pen line'],
  ['pen-off', 'pen off'],
  ['pen-square', 'pen square'],
  ['pen-tool', 'pen tool'],
  ['pencil', 'pencil'],
  ['pencil-line', 'pencil line'],
  ['pencil-off', 'pencil off'],
  ['pencil-ruler', 'pencil ruler'],
  ['pencil-sparkles', 'pencil sparkles'],
  ['pentagon', 'pentagon'],
  ['percent', 'percent'],
  ['percent-circle', 'percent circle'],
  ['percent-diamond', 'percent diamond'],
  ['percent-square', 'percent square'],
  ['person-standing', 'person standing'],
  ['phi', 'phi'],
  ['philippine-peso', 'philippine peso'],
  ['phone', 'phone telefone contato ligacao'],
  ['phone-call', 'phone call'],
  ['phone-forwarded', 'phone forwarded'],
  ['phone-incoming', 'phone incoming'],
  ['phone-missed', 'phone missed'],
  ['phone-off', 'phone off'],
  ['phone-outgoing', 'phone outgoing'],
  ['pi', 'pi'],
  ['pi-square', 'pi square'],
  ['piano', 'piano'],
  ['pickaxe', 'pickaxe'],
  ['picture-in-picture', 'picture in picture'],
  ['picture-in-picture-2', 'picture in picture 2'],
  ['pie-chart', 'pie chart'],
  ['piggy-bank', 'piggy bank'],
  ['pilcrow', 'pilcrow'],
  ['pilcrow-left', 'pilcrow left'],
  ['pilcrow-right', 'pilcrow right'],
  ['pilcrow-square', 'pilcrow square'],
  ['pill', 'pill remedio medicamento farmacia'],
  ['pill-bottle', 'pill bottle'],
  ['pin', 'pin'],
  ['pin-off', 'pin off'],
  ['pipette', 'pipette'],
  ['pizza', 'pizza'],
  ['plane', 'plane aviao viagem voo'],
  ['plane-landing', 'plane landing'],
  ['plane-takeoff', 'plane takeoff'],
  ['plant-pot', 'plant pot'],
  ['play', 'play'],
  ['play-circle', 'play circle'],
  ['play-off', 'play off'],
  ['play-square', 'play square'],
  ['playing-card', 'playing card'],
  ['playing-cards', 'playing cards'],
  ['playing-cards-fan', 'playing cards fan'],
  ['plug', 'plug'],
  ['plug-2', 'plug 2'],
  ['plug-zap', 'plug zap'],
  ['plug-zap-2', 'plug zap 2'],
  ['plus', 'plus'],
  ['plus-circle', 'plus circle'],
  ['plus-square', 'plus square'],
  ['pocket', 'pocket'],
  ['pocket-knife', 'pocket knife'],
  ['podcast', 'podcast'],
  ['podium', 'podium'],
  ['pointer', 'pointer'],
  ['pointer-off', 'pointer off'],
  ['popcorn', 'popcorn'],
  ['popsicle', 'popsicle'],
  ['pound-sterling', 'pound sterling'],
  ['power', 'power'],
  ['power-circle', 'power circle'],
  ['power-off', 'power off'],
  ['power-square', 'power square'],
  ['presentation', 'presentation'],
  ['printer', 'printer'],
  ['printer-check', 'printer check'],
  ['printer-x', 'printer x'],
  ['projector', 'projector'],
  ['proportions', 'proportions'],
  ['puzzle', 'puzzle'],
  ['pyramid', 'pyramid'],
  ['qr-code', 'qr code'],
  ['quote', 'quote'],
  ['rabbit', 'rabbit'],
  ['radar', 'radar'],
  ['radiation', 'radiation'],
  ['radical', 'radical'],
  ['radio', 'radio'],
  ['radio-off', 'radio off'],
  ['radio-receiver', 'radio receiver'],
  ['radio-tower', 'radio tower'],
  ['radius', 'radius'],
  ['rail-symbol', 'rail symbol'],
  ['rainbow', 'rainbow'],
  ['rat', 'rat'],
  ['ratio', 'ratio'],
  ['receipt', 'receipt nota fiscal recibo comprovante'],
  ['receipt-cent', 'receipt cent'],
  ['receipt-euro', 'receipt euro'],
  ['receipt-indian-rupee', 'receipt indian rupee'],
  ['receipt-japanese-yen', 'receipt japanese yen'],
  ['receipt-pound-sterling', 'receipt pound sterling'],
  ['receipt-russian-ruble', 'receipt russian ruble'],
  ['receipt-swiss-franc', 'receipt swiss franc'],
  ['receipt-text', 'receipt text'],
  ['receipt-turkish-lira', 'receipt turkish lira'],
  ['rectangle-circle', 'rectangle circle'],
  ['rectangle-ellipsis', 'rectangle ellipsis'],
  ['rectangle-goggles', 'rectangle goggles'],
  ['rectangle-horizontal', 'rectangle horizontal'],
  ['rectangle-vertical', 'rectangle vertical'],
  ['recycle', 'recycle'],
  ['redo', 'redo'],
  ['redo-2', 'redo 2'],
  ['redo-dot', 'redo dot'],
  ['refresh-ccw', 'refresh ccw'],
  ['refresh-ccw-dot', 'refresh ccw dot'],
  ['refresh-cw', 'refresh cw'],
  ['refresh-cw-off', 'refresh cw off'],
  ['refrigerator', 'refrigerator'],
  ['regex', 'regex'],
  ['remove-formatting', 'remove formatting'],
  ['repeat', 'repeat'],
  ['repeat-1', 'repeat 1'],
  ['repeat-2', 'repeat 2'],
  ['repeat-off', 'repeat off'],
  ['replace', 'replace'],
  ['replace-all', 'replace all'],
  ['reply', 'reply'],
  ['reply-all', 'reply all'],
  ['rewind', 'rewind'],
  ['ribbon', 'ribbon'],
  ['road', 'road'],
  ['robot-arm', 'robot arm'],
  ['robot-vacuum', 'robot vacuum'],
  ['rocket', 'rocket'],
  ['rocking-chair', 'rocking chair'],
  ['roller-coaster', 'roller coaster'],
  ['rose', 'rose'],
  ['rotate-3-d', 'rotate 3 d'],
  ['rotate-3d', 'rotate 3d'],
  ['rotate-ccw', 'rotate ccw'],
  ['rotate-ccw-clock', 'rotate ccw clock'],
  ['rotate-ccw-key', 'rotate ccw key'],
  ['rotate-ccw-square', 'rotate ccw square'],
  ['rotate-cw', 'rotate cw'],
  ['rotate-cw-fading-clock', 'rotate cw fading clock'],
  ['rotate-cw-square', 'rotate cw square'],
  ['route', 'route'],
  ['route-off', 'route off'],
  ['router', 'router'],
  ['rows', 'rows'],
  ['rows-2', 'rows 2'],
  ['rows-3', 'rows 3'],
  ['rows-4', 'rows 4'],
  ['rss', 'rss'],
  ['ruler', 'ruler'],
  ['ruler-dimension-line', 'ruler dimension line'],
  ['russian-ruble', 'russian ruble'],
  ['sailboat', 'sailboat'],
  ['salad', 'salad'],
  ['sandwich', 'sandwich'],
  ['satellite', 'satellite'],
  ['satellite-dish', 'satellite dish'],
  ['saudi-riyal', 'saudi riyal'],
  ['save', 'save'],
  ['save-all', 'save all'],
  ['save-check', 'save check'],
  ['save-off', 'save off'],
  ['save-pen', 'save pen'],
  ['save-plus', 'save plus'],
  ['scale', 'scale balanca justica juridico peso'],
  ['scale-3-d', 'scale 3 d'],
  ['scale-3d', 'scale 3d'],
  ['scaling', 'scaling'],
  ['scan', 'scan'],
  ['scan-barcode', 'scan barcode'],
  ['scan-box', 'scan box'],
  ['scan-eye', 'scan eye'],
  ['scan-face', 'scan face'],
  ['scan-heart', 'scan heart'],
  ['scan-line', 'scan line'],
  ['scan-qr-code', 'scan qr code'],
  ['scan-search', 'scan search'],
  ['scan-square', 'scan square'],
  ['scan-text', 'scan text'],
  ['scatter-chart', 'scatter chart'],
  ['school', 'school'],
  ['school-2', 'school 2'],
  ['scissors', 'scissors corte tesoura'],
  ['scissors-line-dashed', 'scissors line dashed'],
  ['scissors-square', 'scissors square'],
  ['scissors-square-dashed-bottom', 'scissors square dashed bottom'],
  ['scooter', 'scooter'],
  ['screen-share', 'screen share'],
  ['screen-share-off', 'screen share off'],
  ['scroll', 'scroll'],
  ['scroll-text', 'scroll text'],
  ['search', 'search busca pesquisa procurar lupa'],
  ['search-alert', 'search alert'],
  ['search-check', 'search check'],
  ['search-code', 'search code'],
  ['search-large', 'search large'],
  ['search-slash', 'search slash'],
  ['search-x', 'search x'],
  ['section', 'section'],
  ['send', 'send'],
  ['send-horizonal', 'send horizonal'],
  ['send-horizontal', 'send horizontal'],
  ['send-to-back', 'send to back'],
  ['separator-horizontal', 'separator horizontal'],
  ['separator-vertical', 'separator vertical'],
  ['server', 'server servidor infra'],
  ['server-cog', 'server cog'],
  ['server-crash', 'server crash'],
  ['server-off', 'server off'],
  ['server-plus', 'server plus'],
  ['settings', 'settings configuracoes ajustes engrenagem'],
  ['settings-2', 'settings 2'],
  ['shapes', 'shapes'],
  ['share', 'share'],
  ['share-2', 'share 2'],
  ['sheet', 'sheet'],
  ['shell', 'shell'],
  ['shelving-unit', 'shelving unit'],
  ['shield', 'shield escudo seguranca protecao'],
  ['shield-alert', 'shield alert'],
  ['shield-ban', 'shield ban'],
  ['shield-check', 'shield check escudo seguranca verificado protecao'],
  ['shield-close', 'shield close'],
  ['shield-cog', 'shield cog'],
  ['shield-cog-corner', 'shield cog corner'],
  ['shield-ellipsis', 'shield ellipsis'],
  ['shield-half', 'shield half'],
  ['shield-keyhole', 'shield keyhole'],
  ['shield-lock', 'shield lock'],
  ['shield-minus', 'shield minus'],
  ['shield-off', 'shield off'],
  ['shield-plus', 'shield plus'],
  ['shield-question', 'shield question'],
  ['shield-question-mark', 'shield question mark'],
  ['shield-user', 'shield user'],
  ['shield-x', 'shield x'],
  ['ship', 'ship navio maritimo porto'],
  ['ship-cargo', 'ship cargo'],
  ['ship-wheel', 'ship wheel'],
  ['shirt', 'shirt'],
  ['shopping-bag', 'shopping bag'],
  ['shopping-basket', 'shopping basket'],
  ['shopping-cart', 'shopping cart compras carrinho vendas'],
  ['shopping-cart-minus', 'shopping cart minus'],
  ['shopping-cart-plus', 'shopping cart plus'],
  ['shovel', 'shovel'],
  ['shower-head', 'shower head'],
  ['shredder', 'shredder'],
  ['shrimp', 'shrimp'],
  ['shrimp-off', 'shrimp off'],
  ['shrink', 'shrink'],
  ['shrub', 'shrub'],
  ['shuffle', 'shuffle'],
  ['sidebar', 'sidebar'],
  ['sidebar-close', 'sidebar close'],
  ['sidebar-open', 'sidebar open'],
  ['sigma', 'sigma'],
  ['sigma-square', 'sigma square'],
  ['signal', 'signal'],
  ['signal-high', 'signal high'],
  ['signal-low', 'signal low'],
  ['signal-medium', 'signal medium'],
  ['signal-zero', 'signal zero'],
  ['signature', 'signature'],
  ['signpost', 'signpost'],
  ['signpost-big', 'signpost big'],
  ['siren', 'siren'],
  ['skip-back', 'skip back'],
  ['skip-forward', 'skip forward'],
  ['skull', 'skull'],
  ['slack', 'slack'],
  ['slash', 'slash'],
  ['slash-square', 'slash square'],
  ['slice', 'slice'],
  ['sliders', 'sliders'],
  ['sliders-horizontal', 'sliders horizontal'],
  ['sliders-vertical', 'sliders vertical'],
  ['smartphone', 'smartphone'],
  ['smartphone-charging', 'smartphone charging'],
  ['smartphone-nfc', 'smartphone nfc'],
  ['smile', 'smile'],
  ['smile-plus', 'smile plus'],
  ['snail', 'snail'],
  ['snowflake', 'snowflake'],
  ['soap-dispenser-droplet', 'soap dispenser droplet'],
  ['sofa', 'sofa'],
  ['solar-panel', 'solar panel'],
  ['sort-asc', 'sort asc'],
  ['sort-desc', 'sort desc'],
  ['soup', 'soup'],
  ['space', 'space'],
  ['spade', 'spade'],
  ['sparkle', 'sparkle'],
  ['sparkles', 'sparkles ia magia novo brilho'],
  ['speaker', 'speaker'],
  ['speech', 'speech'],
  ['spell-check', 'spell check'],
  ['spell-check-2', 'spell check 2'],
  ['spline', 'spline'],
  ['spline-pointer', 'spline pointer'],
  ['split', 'split'],
  ['split-square-horizontal', 'split square horizontal'],
  ['split-square-vertical', 'split square vertical'],
  ['spool', 'spool'],
  ['sport-shoe', 'sport shoe'],
  ['spotlight', 'spotlight'],
  ['spray-can', 'spray can'],
  ['sprout', 'sprout'],
  ['square', 'square'],
  ['square-activity', 'square activity'],
  ['square-arrow-down', 'square arrow down'],
  ['square-arrow-down-left', 'square arrow down left'],
  ['square-arrow-down-right', 'square arrow down right'],
  ['square-arrow-left', 'square arrow left'],
  ['square-arrow-out-down-left', 'square arrow out down left'],
  ['square-arrow-out-down-right', 'square arrow out down right'],
  ['square-arrow-out-up-left', 'square arrow out up left'],
  ['square-arrow-out-up-right', 'square arrow out up right'],
  ['square-arrow-right', 'square arrow right'],
  ['square-arrow-right-enter', 'square arrow right enter'],
  ['square-arrow-right-exit', 'square arrow right exit'],
  ['square-arrow-up', 'square arrow up'],
  ['square-arrow-up-left', 'square arrow up left'],
  ['square-arrow-up-right', 'square arrow up right'],
  ['square-asterisk', 'square asterisk'],
  ['square-bookmark', 'square bookmark'],
  ['square-bottom-dashed-scissors', 'square bottom dashed scissors'],
  ['square-centerline-dashed-horizontal', 'square centerline dashed horizontal'],
  ['square-centerline-dashed-vertical', 'square centerline dashed vertical'],
  ['square-chart-gantt', 'square chart gantt'],
  ['square-check', 'square check'],
  ['square-check-big', 'square check big'],
  ['square-chevron-down', 'square chevron down'],
  ['square-chevron-left', 'square chevron left'],
  ['square-chevron-right', 'square chevron right'],
  ['square-chevron-up', 'square chevron up'],
  ['square-code', 'square code'],
  ['square-dashed', 'square dashed'],
  ['square-dashed-bottom', 'square dashed bottom'],
  ['square-dashed-bottom-code', 'square dashed bottom code'],
  ['square-dashed-kanban', 'square dashed kanban'],
  ['square-dashed-mouse-pointer', 'square dashed mouse pointer'],
  ['square-dashed-text', 'square dashed text'],
  ['square-dashed-top-solid', 'square dashed top solid'],
  ['square-dimensions', 'square dimensions'],
  ['square-divide', 'square divide'],
  ['square-dot', 'square dot'],
  ['square-equal', 'square equal'],
  ['square-exclamation-point', 'square exclamation point'],
  ['square-function', 'square function'],
  ['square-gantt', 'square gantt'],
  ['square-gantt-chart', 'square gantt chart'],
  ['square-kanban', 'square kanban'],
  ['square-kanban-dashed', 'square kanban dashed'],
  ['square-library', 'square library'],
  ['square-m', 'square m'],
  ['square-menu', 'square menu'],
  ['square-minus', 'square minus'],
  ['square-mouse-pointer', 'square mouse pointer'],
  ['square-off', 'square off'],
  ['square-parking', 'square parking'],
  ['square-parking-off', 'square parking off'],
  ['square-pause', 'square pause'],
  ['square-pen', 'square pen'],
  ['square-percent', 'square percent'],
  ['square-pi', 'square pi'],
  ['square-pilcrow', 'square pilcrow'],
  ['square-play', 'square play'],
  ['square-plus', 'square plus'],
  ['square-power', 'square power'],
  ['square-radical', 'square radical'],
  ['square-round-corner', 'square round corner'],
  ['square-scissors', 'square scissors'],
  ['square-sigma', 'square sigma'],
  ['square-slash', 'square slash'],
  ['square-split-horizontal', 'square split horizontal'],
  ['square-split-vertical', 'square split vertical'],
  ['square-square', 'square square'],
  ['square-stack', 'square stack'],
  ['square-star', 'square star'],
  ['square-stop', 'square stop'],
  ['square-terminal', 'square terminal'],
  ['square-text', 'square text'],
  ['square-user', 'square user'],
  ['square-user-round', 'square user round'],
  ['square-x', 'square x'],
  ['squares-exclude', 'squares exclude'],
  ['squares-intersect', 'squares intersect'],
  ['squares-subtract', 'squares subtract'],
  ['squares-unite', 'squares unite'],
  ['squircle', 'squircle'],
  ['squircle-dashed', 'squircle dashed'],
  ['squirrel', 'squirrel'],
  ['stamp', 'stamp'],
  ['star', 'star favorito estrela destaque'],
  ['star-check', 'star check'],
  ['star-half', 'star half'],
  ['star-minus', 'star minus'],
  ['star-off', 'star off'],
  ['star-plus', 'star plus'],
  ['star-x', 'star x'],
  ['stars', 'stars'],
  ['step-back', 'step back'],
  ['step-forward', 'step forward'],
  ['stethoscope', 'stethoscope medico atendimento consulta saude'],
  ['sticker', 'sticker'],
  ['sticky-note', 'sticky note'],
  ['sticky-note-check', 'sticky note check'],
  ['sticky-note-minus', 'sticky note minus'],
  ['sticky-note-off', 'sticky note off'],
  ['sticky-note-plus', 'sticky note plus'],
  ['sticky-note-x', 'sticky note x'],
  ['sticky-notes', 'sticky notes'],
  ['stone', 'stone'],
  ['stop-circle', 'stop circle'],
  ['store', 'store loja comercio varejo'],
  ['stretch-horizontal', 'stretch horizontal'],
  ['stretch-vertical', 'stretch vertical'],
  ['strikethrough', 'strikethrough'],
  ['subscript', 'subscript'],
  ['subtitles', 'subtitles'],
  ['summary', 'summary'],
  ['sun', 'sun'],
  ['sun-dim', 'sun dim'],
  ['sun-medium', 'sun medium'],
  ['sun-moon', 'sun moon'],
  ['sun-snow', 'sun snow'],
  ['sunrise', 'sunrise'],
  ['sunset', 'sunset'],
  ['superscript', 'superscript'],
  ['swatch-book', 'swatch book'],
  ['swiss-franc', 'swiss franc'],
  ['switch-camera', 'switch camera'],
  ['sword', 'sword'],
  ['swords', 'swords'],
  ['syringe', 'syringe'],
  ['table', 'table'],
  ['table-2', 'table 2'],
  ['table-cells-merge', 'table cells merge'],
  ['table-cells-split', 'table cells split'],
  ['table-columns-split', 'table columns split'],
  ['table-config', 'table config'],
  ['table-of-contents', 'table of contents'],
  ['table-properties', 'table properties'],
  ['table-rows-split', 'table rows split'],
  ['tablet', 'tablet'],
  ['tablet-smartphone', 'tablet smartphone'],
  ['tablets', 'tablets'],
  ['tag', 'tag'],
  ['tag-plus', 'tag plus'],
  ['tag-x', 'tag x'],
  ['tags', 'tags'],
  ['tally-1', 'tally 1'],
  ['tally-2', 'tally 2'],
  ['tally-3', 'tally 3'],
  ['tally-4', 'tally 4'],
  ['tally-5', 'tally 5'],
  ['tangent', 'tangent'],
  ['target', 'target'],
  ['telescope', 'telescope'],
  ['tent', 'tent'],
  ['tent-tree', 'tent tree'],
  ['terminal', 'terminal'],
  ['terminal-square', 'terminal square'],
  ['test-tube', 'test tube'],
  ['test-tube-2', 'test tube 2'],
  ['test-tube-diagonal', 'test tube diagonal'],
  ['test-tubes', 'test tubes'],
  ['text', 'text'],
  ['text-align-center', 'text align center'],
  ['text-align-end', 'text align end'],
  ['text-align-justify', 'text align justify'],
  ['text-align-start', 'text align start'],
  ['text-cursor', 'text cursor'],
  ['text-cursor-input', 'text cursor input'],
  ['text-initial', 'text initial'],
  ['text-quote', 'text quote'],
  ['text-search', 'text search'],
  ['text-select', 'text select'],
  ['text-selection', 'text selection'],
  ['text-wrap', 'text wrap'],
  ['theater', 'theater'],
  ['thermometer', 'thermometer'],
  ['thermometer-snowflake', 'thermometer snowflake'],
  ['thermometer-sun', 'thermometer sun'],
  ['thumbs-down', 'thumbs down'],
  ['thumbs-up', 'thumbs up'],
  ['tic-tac-toe', 'tic tac toe'],
  ['ticket', 'ticket'],
  ['ticket-check', 'ticket check'],
  ['ticket-minus', 'ticket minus'],
  ['ticket-percent', 'ticket percent'],
  ['ticket-plus', 'ticket plus'],
  ['ticket-slash', 'ticket slash'],
  ['ticket-x', 'ticket x'],
  ['tickets', 'tickets'],
  ['tickets-plane', 'tickets plane'],
  ['timeline', 'timeline'],
  ['timer', 'timer'],
  ['timer-off', 'timer off'],
  ['timer-reset', 'timer reset'],
  ['toggle-left', 'toggle left'],
  ['toggle-right', 'toggle right'],
  ['toilet', 'toilet'],
  ['tool-case', 'tool case'],
  ['toolbox', 'toolbox'],
  ['toothbrush', 'toothbrush'],
  ['toothbrush-sparkles', 'toothbrush sparkles'],
  ['tornado', 'tornado'],
  ['torus', 'torus'],
  ['touchpad', 'touchpad'],
  ['touchpad-off', 'touchpad off'],
  ['towel-rack', 'towel rack'],
  ['tower-control', 'tower control'],
  ['toy-brick', 'toy brick'],
  ['tractor', 'tractor'],
  ['traffic-cone', 'traffic cone'],
  ['trailer', 'trailer'],
  ['train', 'train'],
  ['train-front', 'train front'],
  ['train-front-tunnel', 'train front tunnel'],
  ['train-track', 'train track'],
  ['tram-front', 'tram front'],
  ['transgender', 'transgender'],
  ['trash', 'trash'],
  ['trash-2', 'trash 2'],
  ['trash-off', 'trash off'],
  ['tree-deciduous', 'tree deciduous'],
  ['tree-palm', 'tree palm'],
  ['tree-pine', 'tree pine'],
  ['trees', 'trees'],
  ['trello', 'trello'],
  ['trending-down', 'trending down'],
  ['trending-up', 'trending up'],
  ['trending-up-down', 'trending up down'],
  ['triangle', 'triangle'],
  ['triangle-alert', 'triangle alert'],
  ['triangle-dashed', 'triangle dashed'],
  ['triangle-right', 'triangle right'],
  ['triangles-centerline-dashed-horizontal', 'triangles centerline dashed horizontal'],
  ['triangles-centerline-dashed-vertical', 'triangles centerline dashed vertical'],
  ['trophy', 'trophy'],
  ['truck', 'truck caminhao logistica frota entrega transporte'],
  ['truck-electric', 'truck electric'],
  ['turkish-lira', 'turkish lira'],
  ['turntable', 'turntable'],
  ['turtle', 'turtle'],
  ['tv', 'tv'],
  ['tv-2', 'tv 2'],
  ['tv-minimal', 'tv minimal'],
  ['tv-minimal-play', 'tv minimal play'],
  ['twitch', 'twitch'],
  ['twitter', 'twitter'],
  ['type', 'type'],
  ['type-outline', 'type outline'],
  ['umbrella', 'umbrella'],
  ['umbrella-off', 'umbrella off'],
  ['underline', 'underline'],
  ['undo', 'undo'],
  ['undo-2', 'undo 2'],
  ['undo-dot', 'undo dot'],
  ['unfold-horizontal', 'unfold horizontal'],
  ['unfold-vertical', 'unfold vertical'],
  ['ungroup', 'ungroup'],
  ['university', 'university'],
  ['unlink', 'unlink'],
  ['unlink-2', 'unlink 2'],
  ['unlock', 'unlock'],
  ['unlock-keyhole', 'unlock keyhole'],
  ['unplug', 'unplug'],
  ['upload', 'upload'],
  ['upload-cloud', 'upload cloud'],
  ['usb', 'usb'],
  ['usb-c-port', 'usb c port'],
  ['user', 'user'],
  ['user-2', 'user 2'],
  ['user-check', 'user check'],
  ['user-check-2', 'user check 2'],
  ['user-circle', 'user circle'],
  ['user-circle-2', 'user circle 2'],
  ['user-cog', 'user cog'],
  ['user-cog-2', 'user cog 2'],
  ['user-group', 'user group'],
  ['user-key', 'user key'],
  ['user-lock', 'user lock'],
  ['user-minus', 'user minus'],
  ['user-minus-2', 'user minus 2'],
  ['user-pen', 'user pen'],
  ['user-plus', 'user plus admissao contratacao nova pessoa'],
  ['user-plus-2', 'user plus 2'],
  ['user-round', 'user round'],
  ['user-round-arrow-left', 'user round arrow left'],
  ['user-round-check', 'user round check'],
  ['user-round-cog', 'user round cog'],
  ['user-round-group', 'user round group'],
  ['user-round-key', 'user round key'],
  ['user-round-minus', 'user round minus'],
  ['user-round-pen', 'user round pen'],
  ['user-round-plus', 'user round plus'],
  ['user-round-search', 'user round search'],
  ['user-round-x', 'user round x'],
  ['user-search', 'user search'],
  ['user-shield', 'user shield'],
  ['user-square', 'user square'],
  ['user-square-2', 'user square 2'],
  ['user-star', 'user star'],
  ['user-x', 'user x'],
  ['user-x-2', 'user x 2'],
  ['users', 'users equipe time pessoas gente rh'],
  ['users-2', 'users 2'],
  ['users-round', 'users round'],
  ['utensils', 'utensils restaurante alimentacao comida'],
  ['utensils-crossed', 'utensils crossed'],
  ['utility-pole', 'utility pole'],
  ['van', 'van'],
  ['variable', 'variable'],
  ['vault', 'vault'],
  ['vector-polygon', 'vector polygon'],
  ['vector-square', 'vector square'],
  ['vegan', 'vegan'],
  ['venetian-mask', 'venetian mask'],
  ['venus', 'venus'],
  ['venus-and-mars', 'venus and mars'],
  ['verified', 'verified'],
  ['vibrate', 'vibrate'],
  ['vibrate-off', 'vibrate off'],
  ['video', 'video video filmagem gravacao'],
  ['video-off', 'video off'],
  ['videotape', 'videotape'],
  ['view', 'view'],
  ['virus', 'virus'],
  ['virus-off', 'virus off'],
  ['voicemail', 'voicemail'],
  ['volleyball', 'volleyball'],
  ['volume', 'volume'],
  ['volume-1', 'volume 1'],
  ['volume-2', 'volume 2'],
  ['volume-off', 'volume off'],
  ['volume-x', 'volume x'],
  ['vote', 'vote'],
  ['wallet', 'wallet'],
  ['wallet-2', 'wallet 2'],
  ['wallet-cards', 'wallet cards'],
  ['wallet-minimal', 'wallet minimal'],
  ['wallpaper', 'wallpaper'],
  ['wand', 'wand'],
  ['wand-2', 'wand 2'],
  ['wand-sparkles', 'wand sparkles'],
  ['warehouse', 'warehouse'],
  ['washing-machine', 'washing machine'],
  ['watch', 'watch'],
  ['waves', 'waves'],
  ['waves-arrow-down', 'waves arrow down'],
  ['waves-arrow-up', 'waves arrow up'],
  ['waves-horizontal', 'waves horizontal'],
  ['waves-ladder', 'waves ladder'],
  ['waves-vertical', 'waves vertical'],
  ['waypoints', 'waypoints'],
  ['webcam', 'webcam'],
  ['webcam-off', 'webcam off'],
  ['webhook', 'webhook'],
  ['webhook-off', 'webhook off'],
  ['weight', 'weight'],
  ['weight-tilde', 'weight tilde'],
  ['wheat', 'wheat'],
  ['wheat-off', 'wheat off'],
  ['whistle', 'whistle'],
  ['whole-word', 'whole word'],
  ['wifi', 'wifi rede internet conexao'],
  ['wifi-cog', 'wifi cog'],
  ['wifi-high', 'wifi high'],
  ['wifi-low', 'wifi low'],
  ['wifi-off', 'wifi off'],
  ['wifi-pen', 'wifi pen'],
  ['wifi-sync', 'wifi sync'],
  ['wifi-zero', 'wifi zero'],
  ['wind', 'wind'],
  ['wind-arrow-down', 'wind arrow down'],
  ['wine', 'wine'],
  ['wine-off', 'wine off'],
  ['workflow', 'workflow fluxo processo automacao'],
  ['worm', 'worm'],
  ['wrap-text', 'wrap text'],
  ['wrench', 'wrench manutencao ferramenta conserto'],
  ['wrench-off', 'wrench off'],
  ['x', 'x'],
  ['x-circle', 'x circle'],
  ['x-line-top', 'x line top'],
  ['x-octagon', 'x octagon'],
  ['x-square', 'x square'],
  ['youtube', 'youtube'],
  ['zap', 'zap raio automacao rapido energia'],
  ['zap-off', 'zap off'],
  ['zodiac-aquarius', 'zodiac aquarius'],
  ['zodiac-aries', 'zodiac aries'],
  ['zodiac-cancer', 'zodiac cancer'],
  ['zodiac-capricorn', 'zodiac capricorn'],
  ['zodiac-gemini', 'zodiac gemini'],
  ['zodiac-leo', 'zodiac leo'],
  ['zodiac-libra', 'zodiac libra'],
  ['zodiac-ophiuchus', 'zodiac ophiuchus'],
  ['zodiac-pisces', 'zodiac pisces'],
  ['zodiac-sagittarius', 'zodiac sagittarius'],
  ['zodiac-scorpio', 'zodiac scorpio'],
  ['zodiac-taurus', 'zodiac taurus'],
  ['zodiac-virgo', 'zodiac virgo'],
  ['zoom-in', 'zoom in'],
  ['zoom-out', 'zoom out'],
]

export const totalDeIcones = biblioteca.length

/**
 * A curadoria: o que aparece antes de qualquer busca.
 *
 * Nenhum produto do mercado oferece a biblioteca inteira de cara — Jira mostra
 * um punhado de avatares, Notion abre no emoji, ClickUp num conjunto pequeno com
 * cor. Quem precisa de mais busca; quem não precisa resolve em um clique.
 */
export const curadoria: string[] = [
  'building-2', 'briefcase', 'users', 'user-plus', 'id-card', 'heart-handshake',
  'life-buoy', 'headset', 'message-circle', 'inbox', 'bell', 'megaphone',
  'scale', 'gavel', 'file-signature', 'file-check', 'shield-check', 'stamp',
  'calculator', 'banknote', 'receipt', 'coins', 'wallet', 'chart-line',
  'truck', 'package', 'factory', 'wrench', 'boxes', 'hard-hat',
  'database', 'server', 'code', 'cloud', 'cpu', 'bug',
  'cross', 'stethoscope', 'pill', 'heart-pulse', 'activity', 'syringe',
  'graduation-cap', 'book-open', 'lightbulb', 'target', 'rocket', 'sparkles',
]


/** Atalhos por assunto. A busca continua varrendo a biblioteca inteira. */
export const categoriasDeIcone: { nome: string, icones: string[] }[] = [
  {
    nome: "Jurídico",
    icones: [
      "scale",
      "gavel",
      "file-check",
      "shield-check",
      "file-text",
      "stamp",
      "landmark"
    ]
  },
  {
    nome: "Pessoas",
    icones: [
      "users",
      "user-plus",
      "id-card",
      "heart-handshake",
      "user",
      "user-check",
      "contact",
      "users-round"
    ]
  },
  {
    nome: "Finanças",
    icones: [
      "calculator",
      "banknote",
      "receipt",
      "chart-line",
      "coins",
      "wallet",
      "credit-card",
      "piggy-bank"
    ]
  },
  {
    nome: "Operação",
    icones: [
      "truck",
      "package",
      "factory",
      "wrench",
      "forklift",
      "container",
      "boxes",
      "hard-hat"
    ]
  },
  {
    nome: "Tecnologia",
    icones: [
      "database",
      "server",
      "code",
      "life-buoy",
      "cpu",
      "terminal",
      "cloud",
      "bug"
    ]
  },
  {
    nome: "Saúde",
    icones: [
      "cross",
      "stethoscope",
      "pill",
      "activity",
      "heart-pulse",
      "syringe",
      "hospital",
      "bandage"
    ]
  }
]
