/**
 * A copy desta tela nos 3 idiomas.
 *
 * casca, painel e pastas são cópia de pastas-do-item (rótulos da tela em
 * 08/10/2026). O resto é desta proposta. Os rótulos do campo, o conteúdo do
 * campo e os nomes dos agentes e dos modelos são dado e não se traduzem.
 *
 * O BENI é masculino: "o BENI", "pedir ao BENI" (correção da redatora em
 * 09/10/2026).
 *
 * Regra 33: nenhum texto de interface leva travessão.
 */
import type { Idioma } from '~/composables/useIdioma'

const ptBR = {
  casca: {
    buscar: 'Buscar...',
    membro: 'Membro',
    configuracoes: 'Configurações',
    ajuda: 'Ajuda',
    menuLateral: 'Menu lateral',
    trilha: 'Trilha',
    voltar: 'Voltar',
    avancar: 'Avançar',
    recarregar: 'Recarregar',
    tema: 'Tema',
    idioma: 'Idioma',
    suporte: 'Suporte',
    notificacoes: 'Notificações',
    categorias: 'Categorias',
    itens: {
      inicio: 'Início',
      spaceflows: 'Spaceflows',
      categorias: 'Categorias',
      tarefas: 'Tarefas',
      agenda: 'Agenda',
      novoMenu: 'Novo Menu 0',
      qaTi: 'QA TI',
      visaoGeral: 'Visão Geral',
      sistema: 'Sistema',
      estrutura: 'Estrutura',
      gestaoDeMembros: 'Gestão de Membros',
      interface: 'Interface',
      emails: 'E-mails',
      integracoes: 'Integrações',
      agentesDeIa: 'Agentes de IA',
      logs: 'Logs',
      credenciais: 'Credenciais',
      releases: 'Releases',
      documentacao: 'Documentação',
    } as Record<string, string>,
  },
  painel: {
    identificacao: 'Identificação',
    id: 'ID',
    origem: 'Origem',
    status: 'Status',
    ativo: 'Ativo',
    emailDaSolicitacao: 'E-mail da solicitação',
    historico: 'Histórico',
    criadoEm: 'Criado em',
    atualizadoEm: 'Atualizado em',
    recolher: 'Recolher painel',
    expandir: 'Expandir painel',
    maisAcoes: 'Mais ações',
  },
  pastas: {
    'rotulo': 'Folders do item',
    'visao-geral': 'Visão Geral',
    'comentarios': 'Comentários',
    'logs': 'Logs de Auditoria',
    'spaceflows': 'Spaceflows',
    'anexos': 'Anexos',
    'notas': 'Notas',
  } as Record<string, string>,
  conteudo: {
    porFavorSelecione: 'Por favor, selecione',
    salvar: 'Salvar',
    salvo: 'Item salvo.',
    foraDaProposta: 'Esta folder não muda nesta proposta.',
    foraDaPropostaDica: 'Os 2 campos HTML estão na Visão Geral.',
  },
  editor: {
    placeholder: 'Escreva, digite "/" para comandos ou Ctrl J para o BENI...',
    placeholderSemIa: 'Escreva ou digite "/" para acessar os comandos...',
    desfazer: 'Desfazer',
    refazer: 'Refazer',
    tipo: 'Tipo do bloco',
    texto: 'Texto',
    titulo1: 'Título 1',
    titulo2: 'Título 2',
    titulo3: 'Título 3',
    lista: 'Lista',
    listaNumerada: 'Lista numerada',
    checklist: 'Checklist',
    citacao: 'Citação',
    blocoDeCodigo: 'Bloco de código',
    divisor: 'Divisor',
    tabela: 'Tabela',
    negrito: 'Negrito',
    italico: 'Itálico',
    sublinhado: 'Sublinhado',
    tachado: 'Tachado',
    codigo: 'Código',
    cor: 'Cor',
    link: 'Link',
    limparFormatacao: 'Limpar formatação',
    emoji: 'Emoji',
    mencao: 'Mencionar pessoa',
    alinhamento: 'Alinhamento',
    alinharEsquerda: 'Alinhar à esquerda',
    centralizar: 'Centralizar',
    alinharDireita: 'Alinhar à direita',
    justificar: 'Justificar',
    mais: 'Mais',
    sobrescrito: 'Sobrescrito',
    subscrito: 'Subscrito',
    recuar: 'Diminuir recuo',
    avancar: 'Aumentar recuo',
    adicionarLinha: 'Adicionar linha',
    adicionarColuna: 'Adicionar coluna',
    excluirLinha: 'Excluir linha',
    excluirColuna: 'Excluir coluna',
    excluirTabela: 'Excluir tabela',
    grupoBasicos: 'Blocos básicos',
    grupoInserir: 'Inserir',
    grupoCor: 'Cor do texto',
    grupoTabela: 'Tabela',
    atalho: (s: string) => `Atalho: ${s}`,
    palavras: (p: number, c: number) => `${p} ${p === 1 ? 'palavra' : 'palavras'} · ${c} ${c === 1 ? 'caractere' : 'caracteres'}`,
  },
  bloco: {
    adicionar: 'Adicionar bloco abaixo',
    arrastar: 'Arraste para mover. Clique para abrir o menu.',
    transformarEm: 'Transformar em',
    cor: 'Cor',
    duplicar: 'Duplicar',
    copiar: 'Copiar texto',
    copiado: 'Texto copiado.',
    moverAcima: 'Mover para cima',
    moverAbaixo: 'Mover para baixo',
    excluir: 'Excluir',
    perguntarAoBeni: 'Perguntar ao BENI',
  },
  cores: {
    nomes: { padrao: 'Padrão', cinza: 'Cinza', marrom: 'Marrom', laranja: 'Laranja', amarelo: 'Amarelo', verde: 'Verde', azul: 'Azul', roxo: 'Roxo', rosa: 'Rosa', vermelho: 'Vermelho' } as Record<string, string>,
    texto: 'Cor do texto',
    fundo: 'Cor de fundo',
    recentes: 'Usadas recentemente',
    corDoTexto: (n: string) => `Texto ${n.toLowerCase()}`,
    corDoFundo: (n: string) => `Fundo ${n.toLowerCase()}`,
    repetir: 'Repete a última cor',
  },
  link: {
    placeholder: 'Cole um link ou busque um item',
    itens: 'Itens do workspace',
    colar: 'Link digitado',
    aplicar: 'Aplicar link',
    abrir: 'Abrir link',
    copiar: 'Copiar link',
    remover: 'Remover link',
    copiado: 'Link copiado.',
    semResultado: 'Nenhum item com esse nome. Cole o endereço completo.',
  },
  beni: {
    botao: 'IA',
    botaoBolha: 'Perguntar ao BENI',
    dica: 'Escrever com o BENI',
    desligada: 'A IA está desligada neste workspace. Quem administra pode ligar em Configurações › Agentes de IA.',
    caixa: 'Caixa do BENI',
    placeholderPedido: 'Peça ao BENI ou escolha uma ação...',
    placeholderSelecao: 'Peça ao BENI o que fazer com o trecho...',
    placeholderAgente: (nome: string) => `Escreva o pedido para ${nome}...`,
    enviar: 'Enviar',
    seuPedido: 'Seu pedido',
    grupoSalvos: 'Seus pedidos salvos',
    grupoEditar: 'Editar o trecho',
    grupoEscrever: 'Escrever',
    grupoAgentes: 'Pedir a um agente',
    grupoMenu: 'BENI (IA)',
    verTodos: (n: number) => `Ver todos os agentes (${n})`,
    pedir: 'Perguntar ao BENI',
    pedirDescricao: 'Escreva o que precisa',
    melhorar: 'Melhorar a escrita',
    corrigir: 'Corrigir ortografia e gramática',
    encurtar: 'Encurtar',
    expandir: 'Expandir',
    simplificar: 'Simplificar a linguagem',
    explicar: 'Explicar',
    lista: 'Transformar em lista',
    tom: 'Mudar o tom',
    tons: { formal: 'Formal', profissional: 'Profissional', amigavel: 'Amigável', direto: 'Direto', confiante: 'Confiante', empatico: 'Empático', didatico: 'Didático', persuasivo: 'Persuasivo' } as Record<string, string>,
    traduzir: 'Traduzir',
    idiomas: { pt: 'Português', en: 'Inglês', es: 'Espanhol', fr: 'Francês', de: 'Alemão', it: 'Italiano' } as Record<string, string>,
    paraTom: (tom: string) => `Tom ${tom.toLowerCase()}`,
    paraIdioma: (idioma: string) => `Traduzir para ${idioma.toLowerCase()}`,
    resumirSelecao: 'Resumir',
    continuar: 'Continuar escrevendo',
    continuarDescricao: 'Segue o texto do campo',
    resumir: 'Resumir o campo',
    resumirDescricao: 'Os pontos principais em lista',
    pendencias: 'Extrair pendências',
    pendenciasDescricao: 'Vira um checklist',
    rascunhar: 'Rascunhar com os dados do item',
    rascunharDescricao: 'Usa fornecedor, valores e vigência',
    escrevendoBeni: 'O BENI está escrevendo...',
    escrevendoAgente: (nome: string) => `${nome} está escrevendo...`,
    parar: 'Parar',
    aceitar: 'Aceitar',
    inserirAbaixo: 'Inserir abaixo',
    descartar: 'Descartar',
    tentarDeNovo: 'Tentar de novo',
    placeholderAjuste: 'Peça um ajuste: mais curto, em lista...',
    util: 'Resposta útil',
    inutil: 'Resposta não ajudou',
    obrigado: 'Obrigado pelo retorno.',
    salvarPedido: 'Salvar pedido',
    nomeDoPedido: 'Nome do pedido',
    salvar: 'Salvar',
    pedidoSalvo: (n: string) => `Pedido "${n}" salvo. Ele aparece no topo da caixa do BENI e no "/".`,
    oQueMudou: 'O que o Revisor mudou',
    interrompido: 'Resposta interrompida.',
    simulacaoTraducao: 'Simulação: a tradução está pronta só nos 2 parágrafos do exemplo.',
    erroTitulo: 'Sem resposta.',
    erroTexto: 'Nada mudou no campo. Tente de novo em instantes.',
    aviso: 'O BENI pode errar. Confira antes de aceitar.',
    fechar: 'fecha',
    contextoTrecho: 'Trecho selecionado',
    contextoCampo: 'Este campo',
    maisCampos: (n: number) => `+${n} campos do item`,
    contextoTitulo: 'O que a IA lê',
    usarCampos: 'Usar os campos do item',
    aceito: 'Texto do BENI aplicado.',
    prontaSr: 'Proposta pronta. Enter aceita, Esc descarta.',
    desfazer: 'Desfazer',
  },
  agente: {
    rotulo: 'Agente',
    beni: 'BENI',
    beniDescricao: 'Assistente padrão do workspace.',
    padrao: 'Padrão',
    tipos: { chat: 'Chat e texto', reviewer: 'Revisor' } as Record<string, string>,
    buscar: 'Buscar agente...',
    nenhum: 'Nenhum agente com esse nome.',
    gerenciar: 'Gerenciar agentes',
    nota: 'Só aparecem agentes ativos que você pode usar.',
  },
  modelo: {
    rotulo: 'Modelo',
    doAgente: 'do agente',
    descricoes: {
      'auto': 'Escolhe o modelo pelo pedido. Equilibra velocidade e consumo.',
      'claude-sonnet-4.6': 'Rápido e equilibrado.',
      'claude-opus-4.6': 'Máxima qualidade de raciocínio.',
      'gpt-5.4': 'A versão mais nova da família GPT.',
      'gpt-5.2': 'Alta capacidade, consumo maior.',
      'gpt-5-mini': 'Equilíbrio entre qualidade e consumo.',
      'gemini-3.1-pro-preview': 'Alta capacidade, em prévia.',
      'gemini-3-flash': 'Respostas rápidas, consumo menor.',
      'deepseek-r1': 'Especializado em raciocínio.',
      'deepseek-v3.2': 'Versátil, para uso geral.',
    } as Record<string, string>,
    velocidade: 'Velocidade',
    inteligencia: 'Inteligência',
    consumo: 'Consumo de en-credits',
    consumos: { 1: 'baixo', 2: 'médio', 3: 'alto' } as Record<number, string>,
    soNestePedido: (m: string) => `Só neste pedido. O perfil do agente continua com ${m}.`,
  },
  andaime: {
    estadoDaIa: 'IA no workspace',
    estados: { ligada: 'Ligada', desligada: 'Desligada', erro: 'Responde com erro' } as Record<string, string>,
    porTras: 'Por trás',
  },
}

export type Textos = typeof ptBR

const en: Textos = {
  casca: {
    buscar: 'Search...',
    membro: 'Member',
    configuracoes: 'Settings',
    ajuda: 'Help',
    menuLateral: 'Side menu',
    trilha: 'Breadcrumb',
    voltar: 'Back',
    avancar: 'Forward',
    recarregar: 'Reload',
    tema: 'Theme',
    idioma: 'Language',
    suporte: 'Support',
    notificacoes: 'Notifications',
    categorias: 'Categories',
    itens: {
      inicio: 'Home',
      spaceflows: 'Spaceflows',
      categorias: 'Categories',
      tarefas: 'Tasks',
      agenda: 'Calendar',
      novoMenu: 'Novo Menu 0',
      qaTi: 'QA TI',
      visaoGeral: 'Overview',
      sistema: 'System',
      estrutura: 'Structure',
      gestaoDeMembros: 'Member Management',
      interface: 'Interface',
      emails: 'Emails',
      integracoes: 'Integrations',
      agentesDeIa: 'AI Agents',
      logs: 'Logs',
      credenciais: 'Credentials',
      releases: 'Releases',
      documentacao: 'Documentation',
    },
  },
  painel: {
    identificacao: 'Identification',
    id: 'ID',
    origem: 'Origin',
    status: 'Status',
    ativo: 'Active',
    emailDaSolicitacao: 'Request email',
    historico: 'History',
    criadoEm: 'Created at',
    atualizadoEm: 'Updated at',
    recolher: 'Collapse panel',
    expandir: 'Expand panel',
    maisAcoes: 'More actions',
  },
  pastas: {
    'rotulo': 'Item folders',
    'visao-geral': 'Overview',
    'comentarios': 'Comments',
    'logs': 'Audit Logs',
    'spaceflows': 'Spaceflows',
    'anexos': 'Attachments',
    'notas': 'Notes',
  },
  conteudo: {
    porFavorSelecione: 'Please select',
    salvar: 'Save',
    salvo: 'Item saved.',
    foraDaProposta: 'This folder does not change in this proposal.',
    foraDaPropostaDica: 'The 2 HTML fields are in the Overview.',
  },
  editor: {
    placeholder: 'Write, type "/" for commands or Ctrl J for BENI...',
    placeholderSemIa: 'Write or type "/" for commands...',
    desfazer: 'Undo',
    refazer: 'Redo',
    tipo: 'Block type',
    texto: 'Text',
    titulo1: 'Heading 1',
    titulo2: 'Heading 2',
    titulo3: 'Heading 3',
    lista: 'Bulleted list',
    listaNumerada: 'Numbered list',
    checklist: 'Checklist',
    citacao: 'Quote',
    blocoDeCodigo: 'Code block',
    divisor: 'Divider',
    tabela: 'Table',
    negrito: 'Bold',
    italico: 'Italic',
    sublinhado: 'Underline',
    tachado: 'Strikethrough',
    codigo: 'Code',
    cor: 'Color',
    link: 'Link',
    limparFormatacao: 'Clear formatting',
    emoji: 'Emoji',
    mencao: 'Mention a person',
    alinhamento: 'Alignment',
    alinharEsquerda: 'Align left',
    centralizar: 'Center',
    alinharDireita: 'Align right',
    justificar: 'Justify',
    mais: 'More',
    sobrescrito: 'Superscript',
    subscrito: 'Subscript',
    recuar: 'Decrease indent',
    avancar: 'Increase indent',
    adicionarLinha: 'Add row',
    adicionarColuna: 'Add column',
    excluirLinha: 'Delete row',
    excluirColuna: 'Delete column',
    excluirTabela: 'Delete table',
    grupoBasicos: 'Basic blocks',
    grupoInserir: 'Insert',
    grupoCor: 'Text color',
    grupoTabela: 'Table',
    atalho: (s: string) => `Shortcut: ${s}`,
    palavras: (p: number, c: number) => `${p} ${p === 1 ? 'word' : 'words'} · ${c} ${c === 1 ? 'character' : 'characters'}`,
  },
  bloco: {
    adicionar: 'Add block below',
    arrastar: 'Drag to move. Click to open the menu.',
    transformarEm: 'Turn into',
    cor: 'Color',
    duplicar: 'Duplicate',
    copiar: 'Copy text',
    copiado: 'Text copied.',
    moverAcima: 'Move up',
    moverAbaixo: 'Move down',
    excluir: 'Delete',
    perguntarAoBeni: 'Ask BENI',
  },
  cores: {
    nomes: { padrao: 'Default', cinza: 'Gray', marrom: 'Brown', laranja: 'Orange', amarelo: 'Yellow', verde: 'Green', azul: 'Blue', roxo: 'Purple', rosa: 'Pink', vermelho: 'Red' },
    texto: 'Text color',
    fundo: 'Background color',
    recentes: 'Recently used',
    corDoTexto: (n: string) => `${n} text`,
    corDoFundo: (n: string) => `${n} background`,
    repetir: 'Repeats the last color',
  },
  link: {
    placeholder: 'Paste a link or search an item',
    itens: 'Workspace items',
    colar: 'Typed link',
    aplicar: 'Apply link',
    abrir: 'Open link',
    copiar: 'Copy link',
    remover: 'Remove link',
    copiado: 'Link copied.',
    semResultado: 'No item with that name. Paste the full address.',
  },
  beni: {
    botao: 'AI',
    botaoBolha: 'Ask BENI',
    dica: 'Write with BENI',
    desligada: 'AI is turned off in this workspace. An admin can turn it on in Settings › AI Agents.',
    caixa: 'BENI box',
    placeholderPedido: 'Ask BENI or pick an action...',
    placeholderSelecao: 'Ask BENI what to do with the selection...',
    placeholderAgente: (nome: string) => `Write your request for ${nome}...`,
    enviar: 'Send',
    seuPedido: 'Your request',
    grupoSalvos: 'Your saved requests',
    grupoEditar: 'Edit the selection',
    grupoEscrever: 'Write',
    grupoAgentes: 'Ask an agent',
    grupoMenu: 'BENI (AI)',
    verTodos: (n: number) => `See all agents (${n})`,
    pedir: 'Ask BENI',
    pedirDescricao: 'Type what you need',
    melhorar: 'Improve writing',
    corrigir: 'Fix spelling and grammar',
    encurtar: 'Make shorter',
    expandir: 'Make longer',
    simplificar: 'Simplify language',
    explicar: 'Explain',
    lista: 'Turn into a list',
    tom: 'Change tone',
    tons: { formal: 'Formal', profissional: 'Professional', amigavel: 'Friendly', direto: 'Direct', confiante: 'Confident', empatico: 'Empathetic', didatico: 'Instructive', persuasivo: 'Persuasive' },
    traduzir: 'Translate',
    idiomas: { pt: 'Portuguese', en: 'English', es: 'Spanish', fr: 'French', de: 'German', it: 'Italian' },
    paraTom: (tom: string) => `${tom} tone`,
    paraIdioma: (idioma: string) => `Translate to ${idioma}`,
    resumirSelecao: 'Summarize',
    continuar: 'Continue writing',
    continuarDescricao: 'Picks up the field text',
    resumir: 'Summarize the field',
    resumirDescricao: 'The key points as a list',
    pendencias: 'Extract action items',
    pendenciasDescricao: 'Becomes a checklist',
    rascunhar: 'Draft from the item data',
    rascunharDescricao: 'Uses supplier, amounts and end date',
    escrevendoBeni: 'BENI is writing...',
    escrevendoAgente: (nome: string) => `${nome} is writing...`,
    parar: 'Stop',
    aceitar: 'Accept',
    inserirAbaixo: 'Insert below',
    descartar: 'Discard',
    tentarDeNovo: 'Try again',
    placeholderAjuste: 'Ask for a change: shorter, as a list...',
    util: 'Helpful answer',
    inutil: 'Not helpful',
    obrigado: 'Thanks for the feedback.',
    salvarPedido: 'Save request',
    nomeDoPedido: 'Request name',
    salvar: 'Save',
    pedidoSalvo: (n: string) => `Request "${n}" saved. It shows at the top of the BENI box and in "/".`,
    oQueMudou: 'What the Reviewer changed',
    interrompido: 'Response stopped.',
    simulacaoTraducao: 'Simulation: translation is ready only for the 2 sample paragraphs.',
    erroTitulo: 'No response.',
    erroTexto: 'Nothing changed in the field. Try again in a moment.',
    aviso: 'BENI can make mistakes. Check before accepting.',
    fechar: 'closes',
    contextoTrecho: 'Selected text',
    contextoCampo: 'This field',
    maisCampos: (n: number) => `+${n} item fields`,
    contextoTitulo: 'What the AI reads',
    usarCampos: 'Use the item fields',
    aceito: 'BENI text applied.',
    prontaSr: 'Proposal ready. Enter accepts, Esc discards.',
    desfazer: 'Undo',
  },
  agente: {
    rotulo: 'Agent',
    beni: 'BENI',
    beniDescricao: 'The workspace default assistant.',
    padrao: 'Default',
    tipos: { chat: 'Chat and text', reviewer: 'Reviewer' },
    buscar: 'Search agent...',
    nenhum: 'No agent with that name.',
    gerenciar: 'Manage agents',
    nota: 'Only active agents you can use are listed.',
  },
  modelo: {
    rotulo: 'Model',
    doAgente: 'agent\'s',
    descricoes: {
      'auto': 'Picks the model for the request. Balances speed and usage.',
      'claude-sonnet-4.6': 'Fast and balanced.',
      'claude-opus-4.6': 'Top reasoning quality.',
      'gpt-5.4': 'The newest GPT version.',
      'gpt-5.2': 'High capability, higher usage.',
      'gpt-5-mini': 'Balance of quality and usage.',
      'gemini-3.1-pro-preview': 'High capability, in preview.',
      'gemini-3-flash': 'Fast answers, lower usage.',
      'deepseek-r1': 'Specialized in reasoning.',
      'deepseek-v3.2': 'Versatile, general use.',
    },
    velocidade: 'Speed',
    inteligencia: 'Intelligence',
    consumo: 'en-credits usage',
    consumos: { 1: 'low', 2: 'medium', 3: 'high' },
    soNestePedido: (m: string) => `This request only. The agent profile keeps ${m}.`,
  },
  andaime: {
    estadoDaIa: 'AI in the workspace',
    estados: { ligada: 'On', desligada: 'Off', erro: 'Responds with error' },
    porTras: 'Behind it',
  },
}

const es: Textos = {
  casca: {
    buscar: 'Buscar...',
    membro: 'Miembro',
    configuracoes: 'Configuración',
    ajuda: 'Ayuda',
    menuLateral: 'Menú lateral',
    trilha: 'Ruta',
    voltar: 'Atrás',
    avancar: 'Adelante',
    recarregar: 'Recargar',
    tema: 'Tema',
    idioma: 'Idioma',
    suporte: 'Soporte',
    notificacoes: 'Notificaciones',
    categorias: 'Categorías',
    itens: {
      inicio: 'Inicio',
      spaceflows: 'Spaceflows',
      categorias: 'Categorías',
      tarefas: 'Tareas',
      agenda: 'Agenda',
      novoMenu: 'Novo Menu 0',
      qaTi: 'QA TI',
      visaoGeral: 'Visión General',
      sistema: 'Sistema',
      estrutura: 'Estructura',
      gestaoDeMembros: 'Gestión de Miembros',
      interface: 'Interfaz',
      emails: 'Correos',
      integracoes: 'Integraciones',
      agentesDeIa: 'Agentes de IA',
      logs: 'Logs',
      credenciais: 'Credenciales',
      releases: 'Releases',
      documentacao: 'Documentación',
    },
  },
  painel: {
    identificacao: 'Identificación',
    id: 'ID',
    origem: 'Origen',
    status: 'Estado',
    ativo: 'Activo',
    emailDaSolicitacao: 'Correo de la solicitud',
    historico: 'Historial',
    criadoEm: 'Creado el',
    atualizadoEm: 'Actualizado el',
    recolher: 'Contraer panel',
    expandir: 'Expandir panel',
    maisAcoes: 'Más acciones',
  },
  pastas: {
    'rotulo': 'Carpetas del ítem',
    'visao-geral': 'Visión General',
    'comentarios': 'Comentarios',
    'logs': 'Logs de Auditoría',
    'spaceflows': 'Spaceflows',
    'anexos': 'Adjuntos',
    'notas': 'Notas',
  },
  conteudo: {
    porFavorSelecione: 'Por favor, seleccione',
    salvar: 'Guardar',
    salvo: 'Ítem guardado.',
    foraDaProposta: 'Esta carpeta no cambia en esta propuesta.',
    foraDaPropostaDica: 'Los 2 campos HTML están en la Visión General.',
  },
  editor: {
    placeholder: 'Escriba, digite "/" para comandos o Ctrl J para BENI...',
    placeholderSemIa: 'Escriba o digite "/" para ver los comandos...',
    desfazer: 'Deshacer',
    refazer: 'Rehacer',
    tipo: 'Tipo de bloque',
    texto: 'Texto',
    titulo1: 'Título 1',
    titulo2: 'Título 2',
    titulo3: 'Título 3',
    lista: 'Lista',
    listaNumerada: 'Lista numerada',
    checklist: 'Lista de tareas',
    citacao: 'Cita',
    blocoDeCodigo: 'Bloque de código',
    divisor: 'Divisor',
    tabela: 'Tabla',
    negrito: 'Negrita',
    italico: 'Cursiva',
    sublinhado: 'Subrayado',
    tachado: 'Tachado',
    codigo: 'Código',
    cor: 'Color',
    link: 'Enlace',
    limparFormatacao: 'Borrar formato',
    emoji: 'Emoji',
    mencao: 'Mencionar persona',
    alinhamento: 'Alineación',
    alinharEsquerda: 'Alinear a la izquierda',
    centralizar: 'Centrar',
    alinharDireita: 'Alinear a la derecha',
    justificar: 'Justificar',
    mais: 'Más',
    sobrescrito: 'Superíndice',
    subscrito: 'Subíndice',
    recuar: 'Reducir sangría',
    avancar: 'Aumentar sangría',
    adicionarLinha: 'Agregar fila',
    adicionarColuna: 'Agregar columna',
    excluirLinha: 'Eliminar fila',
    excluirColuna: 'Eliminar columna',
    excluirTabela: 'Eliminar tabla',
    grupoBasicos: 'Bloques básicos',
    grupoInserir: 'Insertar',
    grupoCor: 'Color del texto',
    grupoTabela: 'Tabla',
    atalho: (s: string) => `Atajo: ${s}`,
    palavras: (p: number, c: number) => `${p} ${p === 1 ? 'palabra' : 'palabras'} · ${c} ${c === 1 ? 'carácter' : 'caracteres'}`,
  },
  bloco: {
    adicionar: 'Agregar bloque debajo',
    arrastar: 'Arrastre para mover. Haga clic para abrir el menú.',
    transformarEm: 'Convertir en',
    cor: 'Color',
    duplicar: 'Duplicar',
    copiar: 'Copiar texto',
    copiado: 'Texto copiado.',
    moverAcima: 'Mover arriba',
    moverAbaixo: 'Mover abajo',
    excluir: 'Eliminar',
    perguntarAoBeni: 'Preguntar a BENI',
  },
  cores: {
    nomes: { padrao: 'Predeterminado', cinza: 'Gris', marrom: 'Marrón', laranja: 'Naranja', amarelo: 'Amarillo', verde: 'Verde', azul: 'Azul', roxo: 'Morado', rosa: 'Rosa', vermelho: 'Rojo' },
    texto: 'Color del texto',
    fundo: 'Color de fondo',
    recentes: 'Usados recientemente',
    corDoTexto: (n: string) => `Texto ${n.toLowerCase()}`,
    corDoFundo: (n: string) => `Fondo ${n.toLowerCase()}`,
    repetir: 'Repite el último color',
  },
  link: {
    placeholder: 'Pegue un enlace o busque un ítem',
    itens: 'Ítems del workspace',
    colar: 'Enlace escrito',
    aplicar: 'Aplicar enlace',
    abrir: 'Abrir enlace',
    copiar: 'Copiar enlace',
    remover: 'Quitar enlace',
    copiado: 'Enlace copiado.',
    semResultado: 'Ningún ítem con ese nombre. Pegue la dirección completa.',
  },
  beni: {
    botao: 'IA',
    botaoBolha: 'Preguntar a BENI',
    dica: 'Escribir con BENI',
    desligada: 'La IA está desactivada en este workspace. Quien administra puede activarla en Configuración › Agentes de IA.',
    caixa: 'Caja de BENI',
    placeholderPedido: 'Pida a BENI o elija una acción...',
    placeholderSelecao: 'Pida a BENI qué hacer con el texto...',
    placeholderAgente: (nome: string) => `Escriba el pedido para ${nome}...`,
    enviar: 'Enviar',
    seuPedido: 'Su pedido',
    grupoSalvos: 'Sus pedidos guardados',
    grupoEditar: 'Editar el texto',
    grupoEscrever: 'Escribir',
    grupoAgentes: 'Pedir a un agente',
    grupoMenu: 'BENI (IA)',
    verTodos: (n: number) => `Ver todos los agentes (${n})`,
    pedir: 'Preguntar a BENI',
    pedirDescricao: 'Escriba lo que necesita',
    melhorar: 'Mejorar la redacción',
    corrigir: 'Corregir ortografía y gramática',
    encurtar: 'Acortar',
    expandir: 'Ampliar',
    simplificar: 'Simplificar el lenguaje',
    explicar: 'Explicar',
    lista: 'Convertir en lista',
    tom: 'Cambiar el tono',
    tons: { formal: 'Formal', profissional: 'Profesional', amigavel: 'Cercano', direto: 'Directo', confiante: 'Seguro', empatico: 'Empático', didatico: 'Didáctico', persuasivo: 'Persuasivo' },
    traduzir: 'Traducir',
    idiomas: { pt: 'Portugués', en: 'Inglés', es: 'Español', fr: 'Francés', de: 'Alemán', it: 'Italiano' },
    paraTom: (tom: string) => `Tono ${tom.toLowerCase()}`,
    paraIdioma: (idioma: string) => `Traducir al ${idioma.toLowerCase()}`,
    resumirSelecao: 'Resumir',
    continuar: 'Seguir escribiendo',
    continuarDescricao: 'Sigue el texto del campo',
    resumir: 'Resumir el campo',
    resumirDescricao: 'Los puntos principales en lista',
    pendencias: 'Extraer pendientes',
    pendenciasDescricao: 'Se convierte en lista de tareas',
    rascunhar: 'Redactar con los datos del ítem',
    rascunharDescricao: 'Usa proveedor, valores y vigencia',
    escrevendoBeni: 'BENI está escribiendo...',
    escrevendoAgente: (nome: string) => `${nome} está escribiendo...`,
    parar: 'Detener',
    aceitar: 'Aceptar',
    inserirAbaixo: 'Insertar debajo',
    descartar: 'Descartar',
    tentarDeNovo: 'Intentar de nuevo',
    placeholderAjuste: 'Pida un ajuste: más corto, en lista...',
    util: 'Respuesta útil',
    inutil: 'No ayudó',
    obrigado: 'Gracias por su opinión.',
    salvarPedido: 'Guardar pedido',
    nomeDoPedido: 'Nombre del pedido',
    salvar: 'Guardar',
    pedidoSalvo: (n: string) => `Pedido "${n}" guardado. Aparece arriba en la caja de BENI y en "/".`,
    oQueMudou: 'Lo que cambió el Revisor',
    interrompido: 'Respuesta detenida.',
    simulacaoTraducao: 'Simulación: la traducción está lista solo en los 2 párrafos del ejemplo.',
    erroTitulo: 'Sin respuesta.',
    erroTexto: 'Nada cambió en el campo. Intente de nuevo en unos instantes.',
    aviso: 'BENI puede equivocarse. Revise antes de aceptar.',
    fechar: 'cierra',
    contextoTrecho: 'Texto seleccionado',
    contextoCampo: 'Este campo',
    maisCampos: (n: number) => `+${n} campos del ítem`,
    contextoTitulo: 'Lo que lee la IA',
    usarCampos: 'Usar los campos del ítem',
    aceito: 'Texto de BENI aplicado.',
    prontaSr: 'Propuesta lista. Enter acepta, Esc descarta.',
    desfazer: 'Deshacer',
  },
  agente: {
    rotulo: 'Agente',
    beni: 'BENI',
    beniDescricao: 'Asistente predeterminado del workspace.',
    padrao: 'Predeterminado',
    tipos: { chat: 'Chat y texto', reviewer: 'Revisor' },
    buscar: 'Buscar agente...',
    nenhum: 'Ningún agente con ese nombre.',
    gerenciar: 'Gestionar agentes',
    nota: 'Solo aparecen agentes activos que puede usar.',
  },
  modelo: {
    rotulo: 'Modelo',
    doAgente: 'del agente',
    descricoes: {
      'auto': 'Elige el modelo según el pedido. Equilibra velocidad y consumo.',
      'claude-sonnet-4.6': 'Rápido y equilibrado.',
      'claude-opus-4.6': 'Máxima calidad de razonamiento.',
      'gpt-5.4': 'La versión más nueva de GPT.',
      'gpt-5.2': 'Alta capacidad, mayor consumo.',
      'gpt-5-mini': 'Equilibrio entre calidad y consumo.',
      'gemini-3.1-pro-preview': 'Alta capacidad, en vista previa.',
      'gemini-3-flash': 'Respuestas rápidas, menor consumo.',
      'deepseek-r1': 'Especializado en razonamiento.',
      'deepseek-v3.2': 'Versátil, uso general.',
    },
    velocidade: 'Velocidad',
    inteligencia: 'Inteligencia',
    consumo: 'Consumo de en-credits',
    consumos: { 1: 'bajo', 2: 'medio', 3: 'alto' },
    soNestePedido: (m: string) => `Solo en este pedido. El perfil del agente sigue con ${m}.`,
  },
  andaime: {
    estadoDaIa: 'IA en el workspace',
    estados: { ligada: 'Activada', desligada: 'Desactivada', erro: 'Responde con error' },
    porTras: 'Detrás',
  },
}

export const textos: Record<Idioma, Textos> = { 'pt-BR': ptBR, en, es }
