/**
 * A copy desta tela nos 3 idiomas.
 *
 * casca, painel e pastas são cópia de pastas-do-item (rótulos da tela em
 * 08/10/2026). editor e beni são desta proposta. Os rótulos do campo e o
 * conteúdo do campo são dado do workspace e não se traduzem.
 *
 * Regra 33: nenhum texto de interface leva travessão.
 */
import type { Idioma } from '~/composables/useIdioma'

const ptBR = {
  casca: {
    buscar: 'Buscar...',
    membro: 'Membro',
    configuracoes: 'Configurações',
    ajuda: 'Ajuda',
    menuLateral: 'Menu lateral',
    trilha: 'Trilha',
    voltar: 'Voltar',
    avancar: 'Avançar',
    recarregar: 'Recarregar',
    tema: 'Tema',
    idioma: 'Idioma',
    suporte: 'Suporte',
    notificacoes: 'Notificações',
    categorias: 'Categorias',
    itens: {
      inicio: 'Início',
      spaceflows: 'Spaceflows',
      categorias: 'Categorias',
      tarefas: 'Tarefas',
      agenda: 'Agenda',
      novoMenu: 'Novo Menu 0',
      qaTi: 'QA TI',
      visaoGeral: 'Visão Geral',
      sistema: 'Sistema',
      estrutura: 'Estrutura',
      gestaoDeMembros: 'Gestão de Membros',
      interface: 'Interface',
      emails: 'E-mails',
      integracoes: 'Integrações',
      agentesDeIa: 'Agentes de IA',
      logs: 'Logs',
      credenciais: 'Credenciais',
      releases: 'Releases',
      documentacao: 'Documentação',
    } as Record<string, string>,
  },
  painel: {
    identificacao: 'Identificação',
    id: 'ID',
    origem: 'Origem',
    status: 'Status',
    ativo: 'Ativo',
    emailDaSolicitacao: 'E-mail da solicitação',
    historico: 'Histórico',
    criadoEm: 'Criado em',
    atualizadoEm: 'Atualizado em',
    recolher: 'Recolher painel',
    expandir: 'Expandir painel',
    maisAcoes: 'Mais ações',
  },
  pastas: {
    'rotulo': 'Folders do item',
    'visao-geral': 'Visão Geral',
    'comentarios': 'Comentários',
    'logs': 'Logs de Auditoria',
    'spaceflows': 'Spaceflows',
    'anexos': 'Anexos',
    'notas': 'Notas',
  } as Record<string, string>,
  conteudo: {
    porFavorSelecione: 'Por favor, selecione',
    salvar: 'Salvar',
    salvo: 'Item salvo.',
    foraDaProposta: 'Esta folder não muda nesta proposta.',
    foraDaPropostaDica: 'Os 2 campos HTML estão na Visão Geral.',
  },
  editor: {
    placeholder: 'Escreva ou digite "/" para acessar os comandos e a IA...',
    placeholderSemIa: 'Escreva ou digite "/" para acessar os comandos...',
    desfazer: 'Desfazer',
    refazer: 'Refazer',
    titulo: 'Título',
    paragrafo: 'Parágrafo',
    titulo1: 'Título 1',
    titulo2: 'Título 2',
    titulo3: 'Título 3',
    negrito: 'Negrito',
    italico: 'Itálico',
    sublinhado: 'Sublinhado',
    tachado: 'Tachado',
    codigo: 'Código',
    emoji: 'Emoji',
    alinhamento: 'Alinhamento',
    alinharEsquerda: 'Alinhar à esquerda',
    centralizar: 'Centralizar',
    alinharDireita: 'Alinhar à direita',
    justificar: 'Justificar',
    mais: 'Mais',
    lista: 'Lista',
    listaNumerada: 'Lista numerada',
    citacao: 'Citação',
    blocoDeCodigo: 'Bloco de código',
    divisor: 'Divisor',
    limparFormatacao: 'Limpar formatação',
    grupoTexto: 'Texto',
    grupoListas: 'Listas',
    grupoInserir: 'Inserir',
  },
  beni: {
    botao: 'IA',
    dica: 'Escrever com a BENI',
    desligada: 'A IA está desligada neste workspace. Quem administra pode ligar em Configurações › Agentes de IA.',
    grupoMenu: 'BENI (IA)',
    grupoSelecao: 'Ajustar o trecho selecionado',
    grupoCampo: 'Escrever no campo',
    pedir: 'Pedir à BENI',
    pedirDescricao: 'Escreva o que precisa',
    continuar: 'Continuar escrevendo',
    continuarDescricao: 'Segue o texto a partir do cursor',
    resumir: 'Resumir o texto',
    resumirDescricao: 'Os pontos principais do campo',
    resumirSelecao: 'Resumir',
    rascunhar: 'Rascunhar com os dados do item',
    rascunharDescricao: 'Usa fornecedor, valores e vigência',
    melhorar: 'Melhorar a escrita',
    corrigir: 'Corrigir ortografia e gramática',
    encurtar: 'Encurtar',
    expandir: 'Expandir',
    tom: 'Mudar o tom',
    tons: { formal: 'Formal', amigavel: 'Amigável', direto: 'Direto' } as Record<string, string>,
    traduzir: 'Traduzir',
    idiomas: { pt: 'Português', en: 'Inglês', es: 'Espanhol' } as Record<string, string>,
    paraTom: (tom: string) => `Tom ${tom.toLowerCase()}`,
    paraIdioma: (idioma: string) => `Traduzir para ${idioma.toLowerCase()}`,
    placeholderPedido: 'Peça à BENI para escrever ou ajustar o texto...',
    placeholderSelecao: 'Peça à BENI o que fazer com o trecho selecionado...',
    placeholderAjuste: 'Peça um ajuste. Ex.: mais curto, em lista',
    enviar: 'Enviar',
    parar: 'Parar',
    escrevendo: 'A BENI está escrevendo...',
    substituir: 'Substituir a seleção',
    inserirAbaixo: 'Inserir abaixo',
    inserir: 'Inserir',
    tentarDeNovo: 'Tentar de novo',
    descartar: 'Descartar',
    aviso: 'A BENI pode errar. Confira antes de salvar.',
    fechar: 'fecha',
    contexto: (n: number) => `Lê este campo e mais ${n} campos do item`,
    contextoSoCampo: 'Lê só este campo',
    contextoTitulo: 'O que a BENI lê',
    contextoCampo: 'Este campo',
    usarCampos: 'Usar os campos do item',
    erroTitulo: 'A BENI não respondeu.',
    erroTexto: 'Nada mudou no campo. Tente de novo em instantes.',
    inserido: 'Texto da BENI inserido.',
    substituido: 'Trecho substituído pela BENI.',
    desfazer: 'Desfazer',
    interrompido: 'Resposta interrompida.',
    simulacaoTraducao: 'Simulação: a tradução está pronta só nos 2 parágrafos do exemplo.',
    sugestoes: 'Sugestões',
    seuPedido: 'Seu pedido',
    caixa: 'Caixa da BENI',
  },
  andaime: {
    estadoDaIa: 'IA no workspace',
    estados: { ligada: 'Ligada', desligada: 'Desligada', erro: 'Responde com erro' } as Record<string, string>,
    porTras: 'Por trás',
  },
}

export type Textos = typeof ptBR

const en: Textos = {
  casca: {
    buscar: 'Search...',
    membro: 'Member',
    configuracoes: 'Settings',
    ajuda: 'Help',
    menuLateral: 'Side menu',
    trilha: 'Breadcrumb',
    voltar: 'Back',
    avancar: 'Forward',
    recarregar: 'Reload',
    tema: 'Theme',
    idioma: 'Language',
    suporte: 'Support',
    notificacoes: 'Notifications',
    categorias: 'Categories',
    itens: {
      inicio: 'Home',
      spaceflows: 'Spaceflows',
      categorias: 'Categories',
      tarefas: 'Tasks',
      agenda: 'Calendar',
      novoMenu: 'Novo Menu 0',
      qaTi: 'QA TI',
      visaoGeral: 'Overview',
      sistema: 'System',
      estrutura: 'Structure',
      gestaoDeMembros: 'Member Management',
      interface: 'Interface',
      emails: 'Emails',
      integracoes: 'Integrations',
      agentesDeIa: 'AI Agents',
      logs: 'Logs',
      credenciais: 'Credentials',
      releases: 'Releases',
      documentacao: 'Documentation',
    },
  },
  painel: {
    identificacao: 'Identification',
    id: 'ID',
    origem: 'Origin',
    status: 'Status',
    ativo: 'Active',
    emailDaSolicitacao: 'Request email',
    historico: 'History',
    criadoEm: 'Created at',
    atualizadoEm: 'Updated at',
    recolher: 'Collapse panel',
    expandir: 'Expand panel',
    maisAcoes: 'More actions',
  },
  pastas: {
    'rotulo': 'Item folders',
    'visao-geral': 'Overview',
    'comentarios': 'Comments',
    'logs': 'Audit Logs',
    'spaceflows': 'Spaceflows',
    'anexos': 'Attachments',
    'notas': 'Notes',
  },
  conteudo: {
    porFavorSelecione: 'Please select',
    salvar: 'Save',
    salvo: 'Item saved.',
    foraDaProposta: 'This folder does not change in this proposal.',
    foraDaPropostaDica: 'The 2 HTML fields are in the Overview.',
  },
  editor: {
    placeholder: 'Write or type "/" for commands and AI...',
    placeholderSemIa: 'Write or type "/" for commands...',
    desfazer: 'Undo',
    refazer: 'Redo',
    titulo: 'Heading',
    paragrafo: 'Paragraph',
    titulo1: 'Heading 1',
    titulo2: 'Heading 2',
    titulo3: 'Heading 3',
    negrito: 'Bold',
    italico: 'Italic',
    sublinhado: 'Underline',
    tachado: 'Strikethrough',
    codigo: 'Code',
    emoji: 'Emoji',
    alinhamento: 'Alignment',
    alinharEsquerda: 'Align left',
    centralizar: 'Center',
    alinharDireita: 'Align right',
    justificar: 'Justify',
    mais: 'More',
    lista: 'Bulleted list',
    listaNumerada: 'Numbered list',
    citacao: 'Quote',
    blocoDeCodigo: 'Code block',
    divisor: 'Divider',
    limparFormatacao: 'Clear formatting',
    grupoTexto: 'Text',
    grupoListas: 'Lists',
    grupoInserir: 'Insert',
  },
  beni: {
    botao: 'AI',
    dica: 'Write with BENI',
    desligada: 'AI is turned off in this workspace. An admin can turn it on in Settings › AI Agents.',
    grupoMenu: 'BENI (AI)',
    grupoSelecao: 'Edit the selected text',
    grupoCampo: 'Write in the field',
    pedir: 'Ask BENI',
    pedirDescricao: 'Type what you need',
    continuar: 'Continue writing',
    continuarDescricao: 'Picks up from the cursor',
    resumir: 'Summarize the text',
    resumirDescricao: 'The key points of the field',
    resumirSelecao: 'Summarize',
    rascunhar: 'Draft from the item data',
    rascunharDescricao: 'Uses supplier, amounts and end date',
    melhorar: 'Improve writing',
    corrigir: 'Fix spelling and grammar',
    encurtar: 'Make shorter',
    expandir: 'Make longer',
    tom: 'Change tone',
    tons: { formal: 'Formal', amigavel: 'Friendly', direto: 'Direct' },
    traduzir: 'Translate',
    idiomas: { pt: 'Portuguese', en: 'English', es: 'Spanish' },
    paraTom: (tom: string) => `${tom} tone`,
    paraIdioma: (idioma: string) => `Translate to ${idioma}`,
    placeholderPedido: 'Ask BENI to write or edit the text...',
    placeholderSelecao: 'Ask BENI what to do with the selected text...',
    placeholderAjuste: 'Ask for a change. E.g.: shorter, as a list',
    enviar: 'Send',
    parar: 'Stop',
    escrevendo: 'BENI is writing...',
    substituir: 'Replace selection',
    inserirAbaixo: 'Insert below',
    inserir: 'Insert',
    tentarDeNovo: 'Try again',
    descartar: 'Discard',
    aviso: 'BENI can make mistakes. Check before saving.',
    fechar: 'closes',
    contexto: (n: number) => `Reads this field and ${n} more item fields`,
    contextoSoCampo: 'Reads only this field',
    contextoTitulo: 'What BENI reads',
    contextoCampo: 'This field',
    usarCampos: 'Use the item fields',
    erroTitulo: 'BENI did not respond.',
    erroTexto: 'Nothing changed in the field. Try again in a moment.',
    inserido: 'BENI text inserted.',
    substituido: 'Text replaced by BENI.',
    desfazer: 'Undo',
    interrompido: 'Response stopped.',
    simulacaoTraducao: 'Simulation: translation is ready only for the 2 sample paragraphs.',
    sugestoes: 'Suggestions',
    seuPedido: 'Your request',
    caixa: 'BENI box',
  },
  andaime: {
    estadoDaIa: 'AI in the workspace',
    estados: { ligada: 'On', desligada: 'Off', erro: 'Responds with error' },
    porTras: 'Behind it',
  },
}

const es: Textos = {
  casca: {
    buscar: 'Buscar...',
    membro: 'Miembro',
    configuracoes: 'Configuración',
    ajuda: 'Ayuda',
    menuLateral: 'Menú lateral',
    trilha: 'Ruta',
    voltar: 'Atrás',
    avancar: 'Adelante',
    recarregar: 'Recargar',
    tema: 'Tema',
    idioma: 'Idioma',
    suporte: 'Soporte',
    notificacoes: 'Notificaciones',
    categorias: 'Categorías',
    itens: {
      inicio: 'Inicio',
      spaceflows: 'Spaceflows',
      categorias: 'Categorías',
      tarefas: 'Tareas',
      agenda: 'Agenda',
      novoMenu: 'Novo Menu 0',
      qaTi: 'QA TI',
      visaoGeral: 'Visión General',
      sistema: 'Sistema',
      estrutura: 'Estructura',
      gestaoDeMembros: 'Gestión de Miembros',
      interface: 'Interfaz',
      emails: 'Correos',
      integracoes: 'Integraciones',
      agentesDeIa: 'Agentes de IA',
      logs: 'Logs',
      credenciais: 'Credenciales',
      releases: 'Releases',
      documentacao: 'Documentación',
    },
  },
  painel: {
    identificacao: 'Identificación',
    id: 'ID',
    origem: 'Origen',
    status: 'Estado',
    ativo: 'Activo',
    emailDaSolicitacao: 'Correo de la solicitud',
    historico: 'Historial',
    criadoEm: 'Creado el',
    atualizadoEm: 'Actualizado el',
    recolher: 'Contraer panel',
    expandir: 'Expandir panel',
    maisAcoes: 'Más acciones',
  },
  pastas: {
    'rotulo': 'Carpetas del ítem',
    'visao-geral': 'Visión General',
    'comentarios': 'Comentarios',
    'logs': 'Logs de Auditoría',
    'spaceflows': 'Spaceflows',
    'anexos': 'Adjuntos',
    'notas': 'Notas',
  },
  conteudo: {
    porFavorSelecione: 'Por favor, seleccione',
    salvar: 'Guardar',
    salvo: 'Ítem guardado.',
    foraDaProposta: 'Esta carpeta no cambia en esta propuesta.',
    foraDaPropostaDica: 'Los 2 campos HTML están en la Visión General.',
  },
  editor: {
    placeholder: 'Escriba o digite "/" para ver los comandos y la IA...',
    placeholderSemIa: 'Escriba o digite "/" para ver los comandos...',
    desfazer: 'Deshacer',
    refazer: 'Rehacer',
    titulo: 'Título',
    paragrafo: 'Párrafo',
    titulo1: 'Título 1',
    titulo2: 'Título 2',
    titulo3: 'Título 3',
    negrito: 'Negrita',
    italico: 'Cursiva',
    sublinhado: 'Subrayado',
    tachado: 'Tachado',
    codigo: 'Código',
    emoji: 'Emoji',
    alinhamento: 'Alineación',
    alinharEsquerda: 'Alinear a la izquierda',
    centralizar: 'Centrar',
    alinharDireita: 'Alinear a la derecha',
    justificar: 'Justificar',
    mais: 'Más',
    lista: 'Lista',
    listaNumerada: 'Lista numerada',
    citacao: 'Cita',
    blocoDeCodigo: 'Bloque de código',
    divisor: 'Divisor',
    limparFormatacao: 'Borrar formato',
    grupoTexto: 'Texto',
    grupoListas: 'Listas',
    grupoInserir: 'Insertar',
  },
  beni: {
    botao: 'IA',
    dica: 'Escribir con BENI',
    desligada: 'La IA está desactivada en este workspace. Quien administra puede activarla en Configuración › Agentes de IA.',
    grupoMenu: 'BENI (IA)',
    grupoSelecao: 'Ajustar el texto seleccionado',
    grupoCampo: 'Escribir en el campo',
    pedir: 'Pedir a BENI',
    pedirDescricao: 'Escriba lo que necesita',
    continuar: 'Seguir escribiendo',
    continuarDescricao: 'Sigue el texto desde el cursor',
    resumir: 'Resumir el texto',
    resumirDescricao: 'Los puntos principales del campo',
    resumirSelecao: 'Resumir',
    rascunhar: 'Redactar con los datos del ítem',
    rascunharDescricao: 'Usa proveedor, valores y vigencia',
    melhorar: 'Mejorar la redacción',
    corrigir: 'Corregir ortografía y gramática',
    encurtar: 'Acortar',
    expandir: 'Ampliar',
    tom: 'Cambiar el tono',
    tons: { formal: 'Formal', amigavel: 'Cercano', direto: 'Directo' },
    traduzir: 'Traducir',
    idiomas: { pt: 'Portugués', en: 'Inglés', es: 'Español' },
    paraTom: (tom: string) => `Tono ${tom.toLowerCase()}`,
    paraIdioma: (idioma: string) => `Traducir al ${idioma.toLowerCase()}`,
    placeholderPedido: 'Pida a BENI que escriba o ajuste el texto...',
    placeholderSelecao: 'Pida a BENI qué hacer con el texto seleccionado...',
    placeholderAjuste: 'Pida un ajuste. Ej.: más corto, en lista',
    enviar: 'Enviar',
    parar: 'Detener',
    escrevendo: 'BENI está escribiendo...',
    substituir: 'Reemplazar la selección',
    inserirAbaixo: 'Insertar debajo',
    inserir: 'Insertar',
    tentarDeNovo: 'Intentar de nuevo',
    descartar: 'Descartar',
    aviso: 'BENI puede equivocarse. Revise antes de guardar.',
    fechar: 'cierra',
    contexto: (n: number) => `Lee este campo y ${n} campos más del ítem`,
    contextoSoCampo: 'Lee solo este campo',
    contextoTitulo: 'Lo que BENI lee',
    contextoCampo: 'Este campo',
    usarCampos: 'Usar los campos del ítem',
    erroTitulo: 'BENI no respondió.',
    erroTexto: 'Nada cambió en el campo. Intente de nuevo en unos instantes.',
    inserido: 'Texto de BENI insertado.',
    substituido: 'Texto reemplazado por BENI.',
    desfazer: 'Deshacer',
    interrompido: 'Respuesta detenida.',
    simulacaoTraducao: 'Simulación: la traducción está lista solo en los 2 párrafos del ejemplo.',
    sugestoes: 'Sugerencias',
    seuPedido: 'Su pedido',
    caixa: 'Caja de BENI',
  },
  andaime: {
    estadoDaIa: 'IA en el workspace',
    estados: { ligada: 'Activada', desligada: 'Desactivada', erro: 'Responde con error' },
    porTras: 'Detrás',
  },
}

export const textos: Record<Idioma, Textos> = { 'pt-BR': ptBR, en, es }
