/**
 * A copy desta tela nos 3 idiomas.
 *
 * Os rótulos da casca e das pastas são os da tela (preview de 08/10/2026),
 * inclusive "folder" em "Nova folder" e "Pesquisar folder...": o protótipo
 * muda o visual da barra, não o vocabulário. A divergência ("folder" numa
 * tela em português) está registrada no BRIEFING como achado.
 *
 * Os nomes das categorias do menu são dado do workspace e não se traduzem.
 *
 * Regra 33: nenhum texto de interface leva travessão.
 */
import type { Idioma } from '~/composables/useIdioma'

const ptBR = {
  casca: {
    buscar: 'Buscar...',
    membro: 'Membro',
    configuracoes: 'Configurações',
    ajuda: 'Ajuda',
    menuLateral: 'Menu lateral',
    trilha: 'Trilha',
    voltar: 'Voltar',
    avancar: 'Avançar',
    recarregar: 'Recarregar',
    tema: 'Tema',
    idioma: 'Idioma',
    suporte: 'Suporte',
    notificacoes: 'Notificações',
    categorias: 'Categorias',
    itens: {
      inicio: 'Início',
      spaceflows: 'Spaceflows',
      categorias: 'Categorias',
      tarefas: 'Tarefas',
      agenda: 'Agenda',
      novoMenu: 'Novo Menu 0',
      qaTi: 'QA TI',
      visaoGeral: 'Visão Geral',
      sistema: 'Sistema',
      estrutura: 'Estrutura',
      gestaoDeMembros: 'Gestão de Membros',
      interface: 'Interface',
      emails: 'E-mails',
      integracoes: 'Integrações',
      agentesDeIa: 'Agentes de IA',
      logs: 'Logs',
      credenciais: 'Credenciais',
      releases: 'Releases',
      documentacao: 'Documentação',
    } as Record<string, string>,
  },
  painel: {
    identificacao: 'Identificação',
    id: 'ID',
    origem: 'Origem',
    status: 'Status',
    ativo: 'Ativo',
    emailDaSolicitacao: 'E-mail da solicitação',
    historico: 'Histórico',
    criadoEm: 'Criado em',
    atualizadoEm: 'Atualizado em',
    recolher: 'Recolher painel',
    expandir: 'Expandir painel',
    maisAcoes: 'Mais ações',
  },
  pastas: {
    'visao-geral': 'Visão Geral',
    'comentarios': 'Comentários',
    'logs': 'Logs de Auditoria',
    'spaceflows': 'Spaceflows',
    'anexos': 'Anexos',
    'notas': 'Notas',
  } as Record<string, string>,
  barra: {
    rotulo: 'Folders do item',
    pesquisar: 'Pesquisar folder...',
    novaFolder: 'Nova folder',
    maisFolders: (n: number) => `Mais ${n} ${n === 1 ? 'folder' : 'folders'}`,
    nenhumaEncontrada: 'Nenhuma folder encontrada.',
    editar: 'Editar',
    ocultar: 'Ocultar',
    excluir: 'Excluir',
    opcoes: (nome: string) => `Opções da folder ${nome}`,
    arrastarDica: 'Arraste para reordenar. Clique com o botão direito para mais opções.',
    movida: (nome: string, pos: number) => `${nome} movida para a posição ${pos}.`,
    ordemSalva: 'Ordem das folders salva.',
    soOcultar: 'Folder do sistema. Você pode ocultar.',
  },
  dialogos: {
    editarTitulo: 'Editar folder',
    novaTitulo: 'Nova folder',
    nome: 'Nome',
    nomePadrao: 'Nova folder',
    salvar: 'Salvar',
    cancelar: 'Cancelar',
    excluirTitulo: (nome: string) => `Excluir a folder ${nome}?`,
    excluirTexto: 'Os campos dela voltam para a Visão Geral. Esta ação não pode ser desfeita.',
    excluirBotao: 'Excluir folder',
    ocultada: (nome: string) => `Folder ${nome} ocultada.`,
    excluida: (nome: string) => `Folder ${nome} excluída.`,
    criada: (nome: string) => `Folder ${nome} criada.`,
    desfazer: 'Desfazer',
  },
  conteudo: {
    porFavorSelecione: 'Por favor, selecione',
    salvar: 'Salvar',
    salvo: 'Item salvo.',
    escrevaComentario: 'Escreva um comentário',
    comentar: 'Comentar',
    adicionarArquivo: 'Adicionar Arquivo',
    documentos: 'Documentos',
    nenhumSpaceflow: 'Nenhum spaceflow rodou neste item.',
    nenhumSpaceflowDica: 'Quando um spaceflow da categoria rodar, a execução aparece aqui.',
    nenhumaNota: 'Nenhuma nota ainda.',
    novaNota: 'Nova nota',
    pastaVazia: 'Esta folder ainda não tem campos.',
    pastaVaziaDica: 'Os campos entram pelo construtor de formulários da categoria.',
  },
  andaime: {
    prototipo: 'Protótipo',
    estilo: 'Estilo da barra',
    estilos: { hoje: 'Hoje', sublinhado: 'Sublinhado', navegador: 'Aba de navegador' },
    recomendada: 'recomendada',
    ondeAbre: 'Onde abre',
    ondes: { tela: 'Tela do item', lateral: 'Barra lateral' },
    porTras: 'Por trás',
  },
}

export type Textos = typeof ptBR

const en: Textos = {
  casca: {
    buscar: 'Search...',
    membro: 'Member',
    configuracoes: 'Settings',
    ajuda: 'Help',
    menuLateral: 'Side menu',
    trilha: 'Breadcrumb',
    voltar: 'Back',
    avancar: 'Forward',
    recarregar: 'Reload',
    tema: 'Theme',
    idioma: 'Language',
    suporte: 'Support',
    notificacoes: 'Notifications',
    categorias: 'Categories',
    itens: {
      inicio: 'Home',
      spaceflows: 'Spaceflows',
      categorias: 'Categories',
      tarefas: 'Tasks',
      agenda: 'Calendar',
      novoMenu: 'Novo Menu 0',
      qaTi: 'QA TI',
      visaoGeral: 'Overview',
      sistema: 'System',
      estrutura: 'Structure',
      gestaoDeMembros: 'Member Management',
      interface: 'Interface',
      emails: 'Emails',
      integracoes: 'Integrations',
      agentesDeIa: 'AI Agents',
      logs: 'Logs',
      credenciais: 'Credentials',
      releases: 'Releases',
      documentacao: 'Documentation',
    },
  },
  painel: {
    identificacao: 'Identification',
    id: 'ID',
    origem: 'Origin',
    status: 'Status',
    ativo: 'Active',
    emailDaSolicitacao: 'Request email',
    historico: 'History',
    criadoEm: 'Created at',
    atualizadoEm: 'Updated at',
    recolher: 'Collapse panel',
    expandir: 'Expand panel',
    maisAcoes: 'More actions',
  },
  pastas: {
    'visao-geral': 'Overview',
    'comentarios': 'Comments',
    'logs': 'Audit Logs',
    'spaceflows': 'Spaceflows',
    'anexos': 'Attachments',
    'notas': 'Notes',
  },
  barra: {
    rotulo: 'Item folders',
    pesquisar: 'Search folder...',
    novaFolder: 'New folder',
    maisFolders: (n: number) => `${n} more ${n === 1 ? 'folder' : 'folders'}`,
    nenhumaEncontrada: 'No folder found.',
    editar: 'Edit',
    ocultar: 'Hide',
    excluir: 'Delete',
    opcoes: (nome: string) => `Options for folder ${nome}`,
    arrastarDica: 'Drag to reorder. Right-click for more options.',
    movida: (nome: string, pos: number) => `${nome} moved to position ${pos}.`,
    ordemSalva: 'Folder order saved.',
    soOcultar: 'System folder. You can hide it.',
  },
  dialogos: {
    editarTitulo: 'Edit folder',
    novaTitulo: 'New folder',
    nome: 'Name',
    nomePadrao: 'New folder',
    salvar: 'Save',
    cancelar: 'Cancel',
    excluirTitulo: (nome: string) => `Delete folder ${nome}?`,
    excluirTexto: 'Its fields go back to the Overview. This action cannot be undone.',
    excluirBotao: 'Delete folder',
    ocultada: (nome: string) => `Folder ${nome} hidden.`,
    excluida: (nome: string) => `Folder ${nome} deleted.`,
    criada: (nome: string) => `Folder ${nome} created.`,
    desfazer: 'Undo',
  },
  conteudo: {
    porFavorSelecione: 'Please select',
    salvar: 'Save',
    salvo: 'Item saved.',
    escrevaComentario: 'Write a comment',
    comentar: 'Comment',
    adicionarArquivo: 'Add File',
    documentos: 'Documents',
    nenhumSpaceflow: 'No spaceflow has run on this item.',
    nenhumSpaceflowDica: 'When a spaceflow from this category runs, the execution shows up here.',
    nenhumaNota: 'No notes yet.',
    novaNota: 'New note',
    pastaVazia: 'This folder has no fields yet.',
    pastaVaziaDica: 'Fields are added in the category form builder.',
  },
  andaime: {
    prototipo: 'Prototype',
    estilo: 'Bar style',
    estilos: { hoje: 'Today', sublinhado: 'Underline', navegador: 'Browser tab' },
    recomendada: 'recommended',
    ondeAbre: 'Opens in',
    ondes: { tela: 'Item page', lateral: 'Sidebar' },
    porTras: 'Behind it',
  },
}

const es: Textos = {
  casca: {
    buscar: 'Buscar...',
    membro: 'Miembro',
    configuracoes: 'Configuración',
    ajuda: 'Ayuda',
    menuLateral: 'Menú lateral',
    trilha: 'Ruta',
    voltar: 'Atrás',
    avancar: 'Adelante',
    recarregar: 'Recargar',
    tema: 'Tema',
    idioma: 'Idioma',
    suporte: 'Soporte',
    notificacoes: 'Notificaciones',
    categorias: 'Categorías',
    itens: {
      inicio: 'Inicio',
      spaceflows: 'Spaceflows',
      categorias: 'Categorías',
      tarefas: 'Tareas',
      agenda: 'Agenda',
      novoMenu: 'Novo Menu 0',
      qaTi: 'QA TI',
      visaoGeral: 'Visión General',
      sistema: 'Sistema',
      estrutura: 'Estructura',
      gestaoDeMembros: 'Gestión de Miembros',
      interface: 'Interfaz',
      emails: 'Correos',
      integracoes: 'Integraciones',
      agentesDeIa: 'Agentes de IA',
      logs: 'Logs',
      credenciais: 'Credenciales',
      releases: 'Releases',
      documentacao: 'Documentación',
    },
  },
  painel: {
    identificacao: 'Identificación',
    id: 'ID',
    origem: 'Origen',
    status: 'Estado',
    ativo: 'Activo',
    emailDaSolicitacao: 'Correo de la solicitud',
    historico: 'Historial',
    criadoEm: 'Creado el',
    atualizadoEm: 'Actualizado el',
    recolher: 'Contraer panel',
    expandir: 'Expandir panel',
    maisAcoes: 'Más acciones',
  },
  pastas: {
    'visao-geral': 'Visión General',
    'comentarios': 'Comentarios',
    'logs': 'Logs de Auditoría',
    'spaceflows': 'Spaceflows',
    'anexos': 'Adjuntos',
    'notas': 'Notas',
  },
  barra: {
    rotulo: 'Carpetas del ítem',
    pesquisar: 'Buscar carpeta...',
    novaFolder: 'Nueva carpeta',
    maisFolders: (n: number) => `${n} ${n === 1 ? 'carpeta' : 'carpetas'} más`,
    nenhumaEncontrada: 'Ninguna carpeta encontrada.',
    editar: 'Editar',
    ocultar: 'Ocultar',
    excluir: 'Eliminar',
    opcoes: (nome: string) => `Opciones de la carpeta ${nome}`,
    arrastarDica: 'Arrastra para reordenar. Clic derecho para más opciones.',
    movida: (nome: string, pos: number) => `${nome} movida a la posición ${pos}.`,
    ordemSalva: 'Orden de las carpetas guardado.',
    soOcultar: 'Carpeta del sistema. Puedes ocultarla.',
  },
  dialogos: {
    editarTitulo: 'Editar carpeta',
    novaTitulo: 'Nueva carpeta',
    nome: 'Nombre',
    nomePadrao: 'Nueva carpeta',
    salvar: 'Guardar',
    cancelar: 'Cancelar',
    excluirTitulo: (nome: string) => `¿Eliminar la carpeta ${nome}?`,
    excluirTexto: 'Sus campos vuelven a la Visión General. Esta acción no se puede deshacer.',
    excluirBotao: 'Eliminar carpeta',
    ocultada: (nome: string) => `Carpeta ${nome} oculta.`,
    excluida: (nome: string) => `Carpeta ${nome} eliminada.`,
    criada: (nome: string) => `Carpeta ${nome} creada.`,
    desfazer: 'Deshacer',
  },
  conteudo: {
    porFavorSelecione: 'Por favor, selecciona',
    salvar: 'Guardar',
    salvo: 'Ítem guardado.',
    escrevaComentario: 'Escribe un comentario',
    comentar: 'Comentar',
    adicionarArquivo: 'Agregar Archivo',
    documentos: 'Documentos',
    nenhumSpaceflow: 'Ningún spaceflow se ejecutó en este ítem.',
    nenhumSpaceflowDica: 'Cuando un spaceflow de la categoría se ejecute, la ejecución aparece aquí.',
    nenhumaNota: 'Todavía no hay notas.',
    novaNota: 'Nueva nota',
    pastaVazia: 'Esta carpeta todavía no tiene campos.',
    pastaVaziaDica: 'Los campos se agregan en el constructor de formularios de la categoría.',
  },
  andaime: {
    prototipo: 'Prototipo',
    estilo: 'Estilo de la barra',
    estilos: { hoje: 'Hoy', sublinhado: 'Subrayado', navegador: 'Pestaña de navegador' },
    recomendada: 'recomendada',
    ondeAbre: 'Dónde se abre',
    ondes: { tela: 'Página del ítem', lateral: 'Barra lateral' },
    porTras: 'Detrás',
  },
}

export const textos: Record<Idioma, Textos> = { 'pt-BR': ptBR, en, es }
